// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: activity_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivityLogsByUser = `-- name: CountActivityLogsByUser :one
SELECT COUNT(*) FROM user_activity_logs WHERE user_id = $1
`

func (q *Queries) CountActivityLogsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityLogsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSecurityLogsByUser = `-- name: CountSecurityLogsByUser :one
SELECT COUNT(*) FROM user_activity_logs
WHERE user_id = $1
  AND action IN ('user.login', 'user.register', 'user.logout',
                 'user.oauth_login', 'user.password_change')
`

func (q *Queries) CountSecurityLogsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSecurityLogsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :exec
INSERT INTO user_activity_logs (user_id, action, resource_type, resource_name,
    ip, ip_region, user_agent, os, browser, device_id, extra)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateActivityLogParams struct {
	UserID       int64       `json:"userId"`
	Action       string      `json:"action"`
	ResourceType pgtype.Text `json:"resourceType"`
	ResourceName pgtype.Text `json:"resourceName"`
	Ip           pgtype.Text `json:"ip"`
	IpRegion     pgtype.Text `json:"ipRegion"`
	UserAgent    pgtype.Text `json:"userAgent"`
	Os           pgtype.Text `json:"os"`
	Browser      pgtype.Text `json:"browser"`
	DeviceID     pgtype.Text `json:"deviceId"`
	Extra        []byte      `json:"extra"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error {
	_, err := q.db.Exec(ctx, createActivityLog,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceName,
		arg.Ip,
		arg.IpRegion,
		arg.UserAgent,
		arg.Os,
		arg.Browser,
		arg.DeviceID,
		arg.Extra,
	)
	return err
}

const listActivityLogsByUser = `-- name: ListActivityLogsByUser :many
SELECT id, user_id, action, resource_type, resource_name, ip, ip_region, user_agent, os, browser, device_id, extra, created_at FROM user_activity_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivityLogsByUserParams struct {
	UserID int64 `json:"userId"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActivityLogsByUser(ctx context.Context, arg ListActivityLogsByUserParams) ([]UserActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserActivityLog
	for rows.Next() {
		var i UserActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceName,
			&i.Ip,
			&i.IpRegion,
			&i.UserAgent,
			&i.Os,
			&i.Browser,
			&i.DeviceID,
			&i.Extra,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecurityLogsByUser = `-- name: ListSecurityLogsByUser :many
SELECT id, user_id, action, resource_type, resource_name, ip, ip_region, user_agent, os, browser, device_id, extra, created_at FROM user_activity_logs
WHERE user_id = $1
  AND action IN ('user.login', 'user.register', 'user.logout',
                 'user.oauth_login', 'user.password_change')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSecurityLogsByUserParams struct {
	UserID int64 `json:"userId"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSecurityLogsByUser(ctx context.Context, arg ListSecurityLogsByUserParams) ([]UserActivityLog, error) {
	rows, err := q.db.Query(ctx, listSecurityLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserActivityLog
	for rows.Next() {
		var i UserActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceName,
			&i.Ip,
			&i.IpRegion,
			&i.UserAgent,
			&i.Os,
			&i.Browser,
			&i.DeviceID,
			&i.Extra,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
