// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaJob = `-- name: CreateMediaJob :one
INSERT INTO media_jobs (slug, transcode_id, status)
VALUES ($1, $2, $3)
RETURNING id, slug, transcode_id, status, error_msg, created_at, updated_at
`

type CreateMediaJobParams struct {
	Slug        string `json:"slug"`
	TranscodeID int64  `json:"transcodeId"`
	Status      string `json:"status"`
}

func (q *Queries) CreateMediaJob(ctx context.Context, arg CreateMediaJobParams) (MediaJob, error) {
	row := q.db.QueryRow(ctx, createMediaJob, arg.Slug, arg.TranscodeID, arg.Status)
	var i MediaJob
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TranscodeID,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobBySlug = `-- name: GetJobBySlug :one
SELECT id, slug, transcode_id, status, error_msg, created_at, updated_at FROM media_jobs WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetJobBySlug(ctx context.Context, slug string) (MediaJob, error) {
	row := q.db.QueryRow(ctx, getJobBySlug, slug)
	var i MediaJob
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TranscodeID,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingJobs = `-- name: GetPendingJobs :many
SELECT mj.id, mj.slug, mj.transcode_id, mj.status, mj.error_msg, mj.created_at, mj.updated_at
FROM media_jobs mj
JOIN media_transcodes mt ON mt.id = mj.transcode_id
WHERE mj.status = 'pending'
  AND mt.status = 'pending'
ORDER BY mj.created_at
LIMIT $1
FOR UPDATE OF mj SKIP LOCKED
`

func (q *Queries) GetPendingJobs(ctx context.Context, limit int32) ([]MediaJob, error) {
	rows, err := q.db.Query(ctx, getPendingJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaJob
	for rows.Next() {
		var i MediaJob
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TranscodeID,
			&i.Status,
			&i.ErrorMsg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE media_jobs
SET status = $2, error_msg = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID       int64       `json:"id"`
	Status   string      `json:"status"`
	ErrorMsg pgtype.Text `json:"errorMsg"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus, arg.ID, arg.Status, arg.ErrorMsg)
	return err
}
