// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: media_transcodes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTranscode = `-- name: CreateTranscode :one
INSERT INTO media_transcodes (slug, physical_file_id, profile, status)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, physical_file_id, profile, status, hls_dir, duration_sec, error_msg, created_at, updated_at
`

type CreateTranscodeParams struct {
	Slug           string `json:"slug"`
	PhysicalFileID int64  `json:"physicalFileId"`
	Profile        string `json:"profile"`
	Status         string `json:"status"`
}

func (q *Queries) CreateTranscode(ctx context.Context, arg CreateTranscodeParams) (MediaTranscode, error) {
	row := q.db.QueryRow(ctx, createTranscode,
		arg.Slug,
		arg.PhysicalFileID,
		arg.Profile,
		arg.Status,
	)
	var i MediaTranscode
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PhysicalFileID,
		&i.Profile,
		&i.Status,
		&i.HlsDir,
		&i.DurationSec,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTranscodeByID = `-- name: GetTranscodeByID :one
SELECT id, slug, physical_file_id, profile, status, hls_dir, duration_sec, error_msg, created_at, updated_at FROM media_transcodes WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTranscodeByID(ctx context.Context, id int64) (MediaTranscode, error) {
	row := q.db.QueryRow(ctx, getTranscodeByID, id)
	var i MediaTranscode
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PhysicalFileID,
		&i.Profile,
		&i.Status,
		&i.HlsDir,
		&i.DurationSec,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTranscodeByPhysicalFileAndProfile = `-- name: GetTranscodeByPhysicalFileAndProfile :one
SELECT id, slug, physical_file_id, profile, status, hls_dir, duration_sec, error_msg, created_at, updated_at FROM media_transcodes
WHERE physical_file_id = $1 AND profile = $2
LIMIT 1
`

type GetTranscodeByPhysicalFileAndProfileParams struct {
	PhysicalFileID int64  `json:"physicalFileId"`
	Profile        string `json:"profile"`
}

func (q *Queries) GetTranscodeByPhysicalFileAndProfile(ctx context.Context, arg GetTranscodeByPhysicalFileAndProfileParams) (MediaTranscode, error) {
	row := q.db.QueryRow(ctx, getTranscodeByPhysicalFileAndProfile, arg.PhysicalFileID, arg.Profile)
	var i MediaTranscode
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PhysicalFileID,
		&i.Profile,
		&i.Status,
		&i.HlsDir,
		&i.DurationSec,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTranscodeBySlug = `-- name: GetTranscodeBySlug :one
SELECT id, slug, physical_file_id, profile, status, hls_dir, duration_sec, error_msg, created_at, updated_at FROM media_transcodes WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTranscodeBySlug(ctx context.Context, slug string) (MediaTranscode, error) {
	row := q.db.QueryRow(ctx, getTranscodeBySlug, slug)
	var i MediaTranscode
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.PhysicalFileID,
		&i.Profile,
		&i.Status,
		&i.HlsDir,
		&i.DurationSec,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTranscodeHLS = `-- name: UpdateTranscodeHLS :exec
UPDATE media_transcodes
SET hls_dir = $2, duration_sec = $3, status = 'done', updated_at = NOW()
WHERE id = $1
`

type UpdateTranscodeHLSParams struct {
	ID          int64       `json:"id"`
	HlsDir      pgtype.Text `json:"hlsDir"`
	DurationSec pgtype.Int4 `json:"durationSec"`
}

func (q *Queries) UpdateTranscodeHLS(ctx context.Context, arg UpdateTranscodeHLSParams) error {
	_, err := q.db.Exec(ctx, updateTranscodeHLS, arg.ID, arg.HlsDir, arg.DurationSec)
	return err
}

const updateTranscodeStatus = `-- name: UpdateTranscodeStatus :exec
UPDATE media_transcodes
SET status = $2, error_msg = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateTranscodeStatusParams struct {
	ID       int64       `json:"id"`
	Status   string      `json:"status"`
	ErrorMsg pgtype.Text `json:"errorMsg"`
}

func (q *Queries) UpdateTranscodeStatus(ctx context.Context, arg UpdateTranscodeStatusParams) error {
	_, err := q.db.Exec(ctx, updateTranscodeStatus, arg.ID, arg.Status, arg.ErrorMsg)
	return err
}
