// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMediaItemsByUser = `-- name: CountMediaItemsByUser :one
SELECT COUNT(*) FROM media_items WHERE user_id = $1
`

func (q *Queries) CountMediaItemsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaItemsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMediaItem = `-- name: CreateMediaItem :one
INSERT INTO media_items (slug, user_id, user_file_id, physical_file_id, transcode_id, title)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, slug, user_id, user_file_id, physical_file_id, transcode_id, title, poster_path, created_at, updated_at
`

type CreateMediaItemParams struct {
	Slug           string      `json:"slug"`
	UserID         int64       `json:"userId"`
	UserFileID     int64       `json:"userFileId"`
	PhysicalFileID int64       `json:"physicalFileId"`
	TranscodeID    pgtype.Int8 `json:"transcodeId"`
	Title          string      `json:"title"`
}

func (q *Queries) CreateMediaItem(ctx context.Context, arg CreateMediaItemParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, createMediaItem,
		arg.Slug,
		arg.UserID,
		arg.UserFileID,
		arg.PhysicalFileID,
		arg.TranscodeID,
		arg.Title,
	)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.UserFileID,
		&i.PhysicalFileID,
		&i.TranscodeID,
		&i.Title,
		&i.PosterPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMediaItem = `-- name: DeleteMediaItem :exec
DELETE FROM media_items WHERE id = $1
`

func (q *Queries) DeleteMediaItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMediaItem, id)
	return err
}

const getMediaItemBySlug = `-- name: GetMediaItemBySlug :one
SELECT mi.id, mi.slug, mi.user_id, mi.user_file_id, mi.physical_file_id, mi.transcode_id, mi.title, mi.poster_path, mi.created_at, mi.updated_at, mt.status AS transcode_status, mt.duration_sec, mt.hls_dir, mt.slug AS transcode_slug
FROM media_items mi
LEFT JOIN media_transcodes mt ON mt.id = mi.transcode_id
WHERE mi.slug = $1
LIMIT 1
`

type GetMediaItemBySlugRow struct {
	ID              int64              `json:"id"`
	Slug            string             `json:"slug"`
	UserID          int64              `json:"userId"`
	UserFileID      int64              `json:"userFileId"`
	PhysicalFileID  int64              `json:"physicalFileId"`
	TranscodeID     pgtype.Int8        `json:"transcodeId"`
	Title           string             `json:"title"`
	PosterPath      pgtype.Text        `json:"posterPath"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	TranscodeStatus pgtype.Text        `json:"transcodeStatus"`
	DurationSec     pgtype.Int4        `json:"durationSec"`
	HlsDir          pgtype.Text        `json:"hlsDir"`
	TranscodeSlug   pgtype.Text        `json:"transcodeSlug"`
}

func (q *Queries) GetMediaItemBySlug(ctx context.Context, slug string) (GetMediaItemBySlugRow, error) {
	row := q.db.QueryRow(ctx, getMediaItemBySlug, slug)
	var i GetMediaItemBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.UserFileID,
		&i.PhysicalFileID,
		&i.TranscodeID,
		&i.Title,
		&i.PosterPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TranscodeStatus,
		&i.DurationSec,
		&i.HlsDir,
		&i.TranscodeSlug,
	)
	return i, err
}

const getMediaItemByTranscodeID = `-- name: GetMediaItemByTranscodeID :one
SELECT id, slug, user_id, user_file_id, physical_file_id, transcode_id, title, poster_path, created_at, updated_at FROM media_items WHERE transcode_id = $1 LIMIT 1
`

func (q *Queries) GetMediaItemByTranscodeID(ctx context.Context, transcodeID pgtype.Int8) (MediaItem, error) {
	row := q.db.QueryRow(ctx, getMediaItemByTranscodeID, transcodeID)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.UserFileID,
		&i.PhysicalFileID,
		&i.TranscodeID,
		&i.Title,
		&i.PosterPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaItemByUserAndFile = `-- name: GetMediaItemByUserAndFile :one
SELECT id, slug, user_id, user_file_id, physical_file_id, transcode_id, title, poster_path, created_at, updated_at FROM media_items
WHERE user_id = $1 AND user_file_id = $2
LIMIT 1
`

type GetMediaItemByUserAndFileParams struct {
	UserID     int64 `json:"userId"`
	UserFileID int64 `json:"userFileId"`
}

func (q *Queries) GetMediaItemByUserAndFile(ctx context.Context, arg GetMediaItemByUserAndFileParams) (MediaItem, error) {
	row := q.db.QueryRow(ctx, getMediaItemByUserAndFile, arg.UserID, arg.UserFileID)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.UserFileID,
		&i.PhysicalFileID,
		&i.TranscodeID,
		&i.Title,
		&i.PosterPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaItemsByUser = `-- name: ListMediaItemsByUser :many
SELECT mi.id, mi.slug, mi.user_id, mi.user_file_id, mi.physical_file_id, mi.transcode_id, mi.title, mi.poster_path, mi.created_at, mi.updated_at, mt.status AS transcode_status, mt.duration_sec, mt.slug AS transcode_slug
FROM media_items mi
LEFT JOIN media_transcodes mt ON mt.id = mi.transcode_id
WHERE mi.user_id = $1
ORDER BY mi.created_at DESC
LIMIT $2 OFFSET $3
`

type ListMediaItemsByUserParams struct {
	UserID int64 `json:"userId"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListMediaItemsByUserRow struct {
	ID              int64              `json:"id"`
	Slug            string             `json:"slug"`
	UserID          int64              `json:"userId"`
	UserFileID      int64              `json:"userFileId"`
	PhysicalFileID  int64              `json:"physicalFileId"`
	TranscodeID     pgtype.Int8        `json:"transcodeId"`
	Title           string             `json:"title"`
	PosterPath      pgtype.Text        `json:"posterPath"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	TranscodeStatus pgtype.Text        `json:"transcodeStatus"`
	DurationSec     pgtype.Int4        `json:"durationSec"`
	TranscodeSlug   pgtype.Text        `json:"transcodeSlug"`
}

func (q *Queries) ListMediaItemsByUser(ctx context.Context, arg ListMediaItemsByUserParams) ([]ListMediaItemsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMediaItemsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMediaItemsByUserRow
	for rows.Next() {
		var i ListMediaItemsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UserID,
			&i.UserFileID,
			&i.PhysicalFileID,
			&i.TranscodeID,
			&i.Title,
			&i.PosterPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TranscodeStatus,
			&i.DurationSec,
			&i.TranscodeSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaItemPoster = `-- name: UpdateMediaItemPoster :exec
UPDATE media_items SET poster_path = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateMediaItemPosterParams struct {
	ID         int64       `json:"id"`
	PosterPath pgtype.Text `json:"posterPath"`
}

func (q *Queries) UpdateMediaItemPoster(ctx context.Context, arg UpdateMediaItemPosterParams) error {
	_, err := q.db.Exec(ctx, updateMediaItemPoster, arg.ID, arg.PosterPath)
	return err
}
