// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MediaItem struct {
	ID             int64              `json:"id"`
	Slug           string             `json:"slug"`
	UserID         int64              `json:"user_id"`
	UserFileID     int64              `json:"user_file_id"`
	PhysicalFileID int64              `json:"physical_file_id"`
	TranscodeID    pgtype.Int8        `json:"transcode_id"`
	Title          string             `json:"title"`
	PosterPath     pgtype.Text        `json:"poster_path"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type MediaJob struct {
	ID          int64              `json:"id"`
	Slug        string             `json:"slug"`
	TranscodeID int64              `json:"transcode_id"`
	Status      string             `json:"status"`
	ErrorMsg    pgtype.Text        `json:"error_msg"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MediaTranscode struct {
	ID             int64              `json:"id"`
	Slug           string             `json:"slug"`
	PhysicalFileID int64              `json:"physical_file_id"`
	Profile        string             `json:"profile"`
	Status         string             `json:"status"`
	HlsDir         pgtype.Text        `json:"hls_dir"`
	DurationSec    pgtype.Int4        `json:"duration_sec"`
	ErrorMsg       pgtype.Text        `json:"error_msg"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PhysicalFile struct {
	ID          int64              `json:"id"`
	Slug        string             `json:"slug"`
	HashAlgo    string             `json:"hash_algo"`
	FileHash    string             `json:"file_hash"`
	PreHash     string             `json:"pre_hash"`
	FileSize    int64              `json:"file_size"`
	MimeType    string             `json:"mime_type"`
	StoragePath string             `json:"storage_path"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UploadTask struct {
	ID             int64              `json:"id"`
	Slug           string             `json:"slug"`
	OwnerUserID    int64              `json:"owner_user_id"`
	HashAlgo       string             `json:"hash_algo"`
	FileHash       string             `json:"file_hash"`
	PreHash        string             `json:"pre_hash"`
	FileSize       int64              `json:"file_size"`
	MimeType       string             `json:"mime_type"`
	TotalChunks    int32              `json:"total_chunks"`
	ChunkSize      int32              `json:"chunk_size"`
	Status         string             `json:"status"`
	PhysicalFileID pgtype.Int8        `json:"physical_file_id"`
	ErrorMsg       pgtype.Text        `json:"error_msg"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Slug         string             `json:"slug"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Status       int16              `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserFile struct {
	ID             int64              `json:"id"`
	Slug           string             `json:"slug"`
	UserID         int64              `json:"user_id"`
	PhysicalFileID pgtype.Int8        `json:"physical_file_id"`
	ParentID       pgtype.Int8        `json:"parent_id"`
	FileName       string             `json:"file_name"`
	IsDir          bool               `json:"is_dir"`
	FileSize       int64              `json:"file_size"`
	MimeType       pgtype.Text        `json:"mime_type"`
	IsStarred      bool               `json:"is_starred"`
	IsTrashed      bool               `json:"is_trashed"`
	TrashedAt      pgtype.Timestamptz `json:"trashed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type UserLevel struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	LevelCode string             `json:"level_code"`
	LevelName string             `json:"level_name"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserProfile struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarPath  pgtype.Text        `json:"avatar_path"`
	Bio         pgtype.Text        `json:"bio"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserStorageStat struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	StorageUsed  int64              `json:"storage_used"`
	StorageQuota int64              `json:"storage_quota"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserTransaction struct {
	ID            int64              `json:"id"`
	Slug          string             `json:"slug"`
	UserID        int64              `json:"user_id"`
	TransactionNo string             `json:"transaction_no"`
	Type          string             `json:"type"`
	AmountCents   int64              `json:"amount_cents"`
	Currency      string             `json:"currency"`
	Status        string             `json:"status"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
