// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MediaItem struct {
	ID             int64              `json:"id"`
	Slug           string             `json:"slug"`
	UserID         int64              `json:"userId"`
	UserFileID     int64              `json:"userFileId"`
	PhysicalFileID int64              `json:"physicalFileId"`
	TranscodeID    pgtype.Int8        `json:"transcodeId"`
	Title          string             `json:"title"`
	PosterPath     pgtype.Text        `json:"posterPath"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type MediaJob struct {
	ID          int64              `json:"id"`
	Slug        string             `json:"slug"`
	TranscodeID int64              `json:"transcodeId"`
	Status      string             `json:"status"`
	ErrorMsg    pgtype.Text        `json:"errorMsg"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type MediaTranscode struct {
	ID             int64              `json:"id"`
	Slug           string             `json:"slug"`
	PhysicalFileID int64              `json:"physicalFileId"`
	Profile        string             `json:"profile"`
	Status         string             `json:"status"`
	HlsDir         pgtype.Text        `json:"hlsDir"`
	DurationSec    pgtype.Int4        `json:"durationSec"`
	ErrorMsg       pgtype.Text        `json:"errorMsg"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

type PhysicalFile struct {
	ID          int64              `json:"id"`
	Slug        string             `json:"slug"`
	HashAlgo    string             `json:"hashAlgo"`
	FileHash    string             `json:"fileHash"`
	PreHash     string             `json:"preHash"`
	FileSize    int64              `json:"fileSize"`
	MimeType    string             `json:"mimeType"`
	StoragePath string             `json:"storagePath"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"userId"`
	TokenHash string             `json:"tokenHash"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	Revoked   bool               `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type UploadTask struct {
	ID             int64              `json:"id"`
	Slug           string             `json:"slug"`
	OwnerUserID    int64              `json:"ownerUserId"`
	HashAlgo       string             `json:"hashAlgo"`
	FileHash       string             `json:"fileHash"`
	PreHash        string             `json:"preHash"`
	FileSize       int64              `json:"fileSize"`
	MimeType       string             `json:"mimeType"`
	TotalChunks    int32              `json:"totalChunks"`
	ChunkSize      int32              `json:"chunkSize"`
	Status         string             `json:"status"`
	PhysicalFileID pgtype.Int8        `json:"physicalFileId"`
	ErrorMsg       pgtype.Text        `json:"errorMsg"`
	ExpiresAt      pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	OriginalName   string             `json:"originalName"`
}

type User struct {
	ID           int64              `json:"id"`
	Slug         string             `json:"slug"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"passwordHash"`
	Status       int16              `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type UserFile struct {
	ID             int64              `json:"id"`
	Slug           string             `json:"slug"`
	UserID         int64              `json:"userId"`
	PhysicalFileID pgtype.Int8        `json:"physicalFileId"`
	ParentID       pgtype.Int8        `json:"parentId"`
	FileName       string             `json:"fileName"`
	IsDir          bool               `json:"isDir"`
	FileSize       int64              `json:"fileSize"`
	MimeType       pgtype.Text        `json:"mimeType"`
	IsStarred      bool               `json:"isStarred"`
	IsTrashed      bool               `json:"isTrashed"`
	TrashedAt      pgtype.Timestamptz `json:"trashedAt"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	FileCategory   string             `json:"fileCategory"`
	ParentSlug     pgtype.Text        `json:"parentSlug"`
}

type UserLevel struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"userId"`
	LevelCode string             `json:"levelCode"`
	LevelName string             `json:"levelName"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type UserProfile struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"userId"`
	DisplayName pgtype.Text        `json:"displayName"`
	AvatarPath  pgtype.Text        `json:"avatarPath"`
	Bio         pgtype.Text        `json:"bio"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type UserStorageStat struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"userId"`
	StorageUsed  int64              `json:"storageUsed"`
	StorageQuota int64              `json:"storageQuota"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type UserTransaction struct {
	ID            int64              `json:"id"`
	Slug          string             `json:"slug"`
	UserID        int64              `json:"userId"`
	TransactionNo string             `json:"transactionNo"`
	Type          string             `json:"type"`
	AmountCents   int64              `json:"amountCents"`
	Currency      string             `json:"currency"`
	Status        string             `json:"status"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}
