// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: oauth_accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO user_oauth_accounts (user_id, provider, provider_account_id, access_token, refresh_token, token_expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, provider, provider_account_id, access_token, refresh_token, token_expires_at, created_at, updated_at
`

type CreateOAuthAccountParams struct {
	UserID            int64              `json:"userId"`
	Provider          string             `json:"provider"`
	ProviderAccountID string             `json:"providerAccountId"`
	AccessToken       string             `json:"accessToken"`
	RefreshToken      string             `json:"refreshToken"`
	TokenExpiresAt    pgtype.Timestamptz `json:"tokenExpiresAt"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (UserOauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderAccountID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i UserOauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthAccountByProviderAndID = `-- name: GetOAuthAccountByProviderAndID :one
SELECT id, user_id, provider, provider_account_id, access_token, refresh_token, token_expires_at, created_at, updated_at
FROM user_oauth_accounts
WHERE provider = $1 AND provider_account_id = $2
LIMIT 1
`

type GetOAuthAccountByProviderAndIDParams struct {
	Provider          string `json:"provider"`
	ProviderAccountID string `json:"providerAccountId"`
}

func (q *Queries) GetOAuthAccountByProviderAndID(ctx context.Context, arg GetOAuthAccountByProviderAndIDParams) (UserOauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccountByProviderAndID, arg.Provider, arg.ProviderAccountID)
	var i UserOauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthAccountsByUserID = `-- name: GetOAuthAccountsByUserID :many
SELECT id, user_id, provider, provider_account_id, access_token, refresh_token, token_expires_at, created_at, updated_at
FROM user_oauth_accounts
WHERE user_id = $1
`

func (q *Queries) GetOAuthAccountsByUserID(ctx context.Context, userID int64) ([]UserOauthAccount, error) {
	rows, err := q.db.Query(ctx, getOAuthAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserOauthAccount
	for rows.Next() {
		var i UserOauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderAccountID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
