// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photo_albums.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPhotoToAlbum = `-- name: AddPhotoToAlbum :one
INSERT INTO photo_album_items (album_id, file_slug, sort_order)
VALUES ($1, $2, $3)
RETURNING id, album_id, file_slug, sort_order, added_at
`

type AddPhotoToAlbumParams struct {
	AlbumID   int64  `json:"albumId"`
	FileSlug  string `json:"fileSlug"`
	SortOrder int32  `json:"sortOrder"`
}

func (q *Queries) AddPhotoToAlbum(ctx context.Context, arg AddPhotoToAlbumParams) (PhotoAlbumItem, error) {
	row := q.db.QueryRow(ctx, addPhotoToAlbum, arg.AlbumID, arg.FileSlug, arg.SortOrder)
	var i PhotoAlbumItem
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.FileSlug,
		&i.SortOrder,
		&i.AddedAt,
	)
	return i, err
}

const countPhotoAlbumItems = `-- name: CountPhotoAlbumItems :one
SELECT COUNT(*) FROM photo_album_items WHERE album_id = $1
`

func (q *Queries) CountPhotoAlbumItems(ctx context.Context, albumID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPhotoAlbumItems, albumID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPhotoAlbumsByUser = `-- name: CountPhotoAlbumsByUser :one
SELECT COUNT(*) FROM photo_albums WHERE user_id = $1
`

func (q *Queries) CountPhotoAlbumsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPhotoAlbumsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPhotoAlbum = `-- name: CreatePhotoAlbum :one
INSERT INTO photo_albums (slug, user_id, title, description)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, user_id, title, description, cover_file_slug, item_count, created_at, updated_at
`

type CreatePhotoAlbumParams struct {
	Slug        string `json:"slug"`
	UserID      int64  `json:"userId"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) CreatePhotoAlbum(ctx context.Context, arg CreatePhotoAlbumParams) (PhotoAlbum, error) {
	row := q.db.QueryRow(ctx, createPhotoAlbum,
		arg.Slug,
		arg.UserID,
		arg.Title,
		arg.Description,
	)
	var i PhotoAlbum
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CoverFileSlug,
		&i.ItemCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementPhotoAlbumItemCount = `-- name: DecrementPhotoAlbumItemCount :exec
UPDATE photo_albums SET item_count = GREATEST(item_count - 1, 0), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DecrementPhotoAlbumItemCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementPhotoAlbumItemCount, id)
	return err
}

const deletePhotoAlbum = `-- name: DeletePhotoAlbum :exec
DELETE FROM photo_albums WHERE slug = $1 AND user_id = $2
`

type DeletePhotoAlbumParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"userId"`
}

func (q *Queries) DeletePhotoAlbum(ctx context.Context, arg DeletePhotoAlbumParams) error {
	_, err := q.db.Exec(ctx, deletePhotoAlbum, arg.Slug, arg.UserID)
	return err
}

const getPhotoAlbumBySlug = `-- name: GetPhotoAlbumBySlug :one
SELECT id, slug, user_id, title, description, cover_file_slug, item_count, created_at, updated_at FROM photo_albums WHERE slug = $1 AND user_id = $2 LIMIT 1
`

type GetPhotoAlbumBySlugParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"userId"`
}

func (q *Queries) GetPhotoAlbumBySlug(ctx context.Context, arg GetPhotoAlbumBySlugParams) (PhotoAlbum, error) {
	row := q.db.QueryRow(ctx, getPhotoAlbumBySlug, arg.Slug, arg.UserID)
	var i PhotoAlbum
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CoverFileSlug,
		&i.ItemCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhotoAlbumItem = `-- name: GetPhotoAlbumItem :one
SELECT pai.id, pai.album_id, pai.file_slug, pai.sort_order, pai.added_at, uf.file_name, uf.file_size, uf.mime_type, uf.file_category,
       uf.created_at AS file_created_at, pf.file_hash
FROM photo_album_items pai
JOIN user_files uf ON uf.slug = pai.file_slug
LEFT JOIN physical_files pf ON pf.id = uf.physical_file_id
WHERE pai.album_id = $1 AND pai.file_slug = $2
LIMIT 1
`

type GetPhotoAlbumItemParams struct {
	AlbumID  int64  `json:"albumId"`
	FileSlug string `json:"fileSlug"`
}

type GetPhotoAlbumItemRow struct {
	ID            int64              `json:"id"`
	AlbumID       int64              `json:"albumId"`
	FileSlug      string             `json:"fileSlug"`
	SortOrder     int32              `json:"sortOrder"`
	AddedAt       pgtype.Timestamptz `json:"addedAt"`
	FileName      string             `json:"fileName"`
	FileSize      int64              `json:"fileSize"`
	MimeType      pgtype.Text        `json:"mimeType"`
	FileCategory  string             `json:"fileCategory"`
	FileCreatedAt pgtype.Timestamptz `json:"fileCreatedAt"`
	FileHash      pgtype.Text        `json:"fileHash"`
}

func (q *Queries) GetPhotoAlbumItem(ctx context.Context, arg GetPhotoAlbumItemParams) (GetPhotoAlbumItemRow, error) {
	row := q.db.QueryRow(ctx, getPhotoAlbumItem, arg.AlbumID, arg.FileSlug)
	var i GetPhotoAlbumItemRow
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.FileSlug,
		&i.SortOrder,
		&i.AddedAt,
		&i.FileName,
		&i.FileSize,
		&i.MimeType,
		&i.FileCategory,
		&i.FileCreatedAt,
		&i.FileHash,
	)
	return i, err
}

const getPhotoAlbumItemCountByFile = `-- name: GetPhotoAlbumItemCountByFile :one
SELECT COUNT(*) FROM photo_album_items WHERE file_slug = $1
`

func (q *Queries) GetPhotoAlbumItemCountByFile(ctx context.Context, fileSlug string) (int64, error) {
	row := q.db.QueryRow(ctx, getPhotoAlbumItemCountByFile, fileSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementPhotoAlbumItemCount = `-- name: IncrementPhotoAlbumItemCount :exec
UPDATE photo_albums SET item_count = item_count + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementPhotoAlbumItemCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementPhotoAlbumItemCount, id)
	return err
}

const listPhotoAlbumItems = `-- name: ListPhotoAlbumItems :many
SELECT pai.id, pai.album_id, pai.file_slug, pai.sort_order, pai.added_at, uf.file_name, uf.file_size, uf.mime_type, uf.file_category,
       uf.created_at AS file_created_at, pf.file_hash
FROM photo_album_items pai
JOIN user_files uf ON uf.slug = pai.file_slug
LEFT JOIN physical_files pf ON pf.id = uf.physical_file_id
WHERE pai.album_id = $1
ORDER BY pai.sort_order ASC, pai.added_at DESC
LIMIT $2 OFFSET $3
`

type ListPhotoAlbumItemsParams struct {
	AlbumID int64 `json:"albumId"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type ListPhotoAlbumItemsRow struct {
	ID            int64              `json:"id"`
	AlbumID       int64              `json:"albumId"`
	FileSlug      string             `json:"fileSlug"`
	SortOrder     int32              `json:"sortOrder"`
	AddedAt       pgtype.Timestamptz `json:"addedAt"`
	FileName      string             `json:"fileName"`
	FileSize      int64              `json:"fileSize"`
	MimeType      pgtype.Text        `json:"mimeType"`
	FileCategory  string             `json:"fileCategory"`
	FileCreatedAt pgtype.Timestamptz `json:"fileCreatedAt"`
	FileHash      pgtype.Text        `json:"fileHash"`
}

func (q *Queries) ListPhotoAlbumItems(ctx context.Context, arg ListPhotoAlbumItemsParams) ([]ListPhotoAlbumItemsRow, error) {
	rows, err := q.db.Query(ctx, listPhotoAlbumItems, arg.AlbumID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPhotoAlbumItemsRow
	for rows.Next() {
		var i ListPhotoAlbumItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.FileSlug,
			&i.SortOrder,
			&i.AddedAt,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.FileCategory,
			&i.FileCreatedAt,
			&i.FileHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotoAlbumsByFile = `-- name: ListPhotoAlbumsByFile :many
SELECT pa.id, pa.slug, pa.user_id, pa.title, pa.description, pa.cover_file_slug, pa.item_count, pa.created_at, pa.updated_at FROM photo_albums pa
JOIN photo_album_items pai ON pai.album_id = pa.id
WHERE pai.file_slug = $1 AND pa.user_id = $2
ORDER BY pa.updated_at DESC
`

type ListPhotoAlbumsByFileParams struct {
	FileSlug string `json:"fileSlug"`
	UserID   int64  `json:"userId"`
}

func (q *Queries) ListPhotoAlbumsByFile(ctx context.Context, arg ListPhotoAlbumsByFileParams) ([]PhotoAlbum, error) {
	rows, err := q.db.Query(ctx, listPhotoAlbumsByFile, arg.FileSlug, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotoAlbum
	for rows.Next() {
		var i PhotoAlbum
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CoverFileSlug,
			&i.ItemCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotoAlbumsByUser = `-- name: ListPhotoAlbumsByUser :many
SELECT id, slug, user_id, title, description, cover_file_slug, item_count, created_at, updated_at FROM photo_albums
WHERE user_id = $1
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListPhotoAlbumsByUserParams struct {
	UserID int64 `json:"userId"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPhotoAlbumsByUser(ctx context.Context, arg ListPhotoAlbumsByUserParams) ([]PhotoAlbum, error) {
	rows, err := q.db.Query(ctx, listPhotoAlbumsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhotoAlbum
	for rows.Next() {
		var i PhotoAlbum
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CoverFileSlug,
			&i.ItemCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePhotoFromAlbum = `-- name: RemovePhotoFromAlbum :exec
DELETE FROM photo_album_items WHERE album_id = $1 AND file_slug = $2
`

type RemovePhotoFromAlbumParams struct {
	AlbumID  int64  `json:"albumId"`
	FileSlug string `json:"fileSlug"`
}

func (q *Queries) RemovePhotoFromAlbum(ctx context.Context, arg RemovePhotoFromAlbumParams) error {
	_, err := q.db.Exec(ctx, removePhotoFromAlbum, arg.AlbumID, arg.FileSlug)
	return err
}

const updatePhotoAlbum = `-- name: UpdatePhotoAlbum :one
UPDATE photo_albums
SET title = $3, description = $4, cover_file_slug = $5, updated_at = NOW()
WHERE slug = $1 AND user_id = $2
RETURNING id, slug, user_id, title, description, cover_file_slug, item_count, created_at, updated_at
`

type UpdatePhotoAlbumParams struct {
	Slug          string      `json:"slug"`
	UserID        int64       `json:"userId"`
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	CoverFileSlug pgtype.Text `json:"coverFileSlug"`
}

func (q *Queries) UpdatePhotoAlbum(ctx context.Context, arg UpdatePhotoAlbumParams) (PhotoAlbum, error) {
	row := q.db.QueryRow(ctx, updatePhotoAlbum,
		arg.Slug,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.CoverFileSlug,
	)
	var i PhotoAlbum
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CoverFileSlug,
		&i.ItemCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
