// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: photos.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countImageFiles = `-- name: CountImageFiles :one
SELECT COUNT(*) FROM user_files
WHERE user_id = $1
  AND is_dir = FALSE
  AND is_trashed = FALSE
  AND file_category = 'image'
`

func (q *Queries) CountImageFiles(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countImageFiles, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listImageFiles = `-- name: ListImageFiles :many
SELECT uf.slug, uf.file_name, uf.file_size, uf.mime_type, uf.file_category,
       uf.is_starred, uf.created_at, uf.updated_at,
       pf.file_hash
FROM user_files uf
LEFT JOIN physical_files pf ON pf.id = uf.physical_file_id
WHERE uf.user_id = $1
  AND uf.is_dir = FALSE
  AND uf.is_trashed = FALSE
  AND uf.file_category = 'image'
ORDER BY uf.created_at DESC
LIMIT $2 OFFSET $3
`

type ListImageFilesParams struct {
	UserID int64 `json:"userId"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListImageFilesRow struct {
	Slug         string             `json:"slug"`
	FileName     string             `json:"fileName"`
	FileSize     int64              `json:"fileSize"`
	MimeType     pgtype.Text        `json:"mimeType"`
	FileCategory string             `json:"fileCategory"`
	IsStarred    bool               `json:"isStarred"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
	FileHash     pgtype.Text        `json:"fileHash"`
}

func (q *Queries) ListImageFiles(ctx context.Context, arg ListImageFilesParams) ([]ListImageFilesRow, error) {
	rows, err := q.db.Query(ctx, listImageFiles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImageFilesRow
	for rows.Next() {
		var i ListImageFilesRow
		if err := rows.Scan(
			&i.Slug,
			&i.FileName,
			&i.FileSize,
			&i.MimeType,
			&i.FileCategory,
			&i.IsStarred,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FileHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
