// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: physical_files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReferencesByFileID = `-- name: CountReferencesByFileID :one
SELECT COUNT(*) FROM user_files WHERE physical_file_id = $1
`

func (q *Queries) CountReferencesByFileID(ctx context.Context, physicalFileID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countReferencesByFileID, physicalFileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPhysicalFile = `-- name: CreatePhysicalFile :one
INSERT INTO physical_files (slug, hash_algo, file_hash, pre_hash, file_size, mime_type, storage_path, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (hash_algo, file_hash) DO NOTHING
RETURNING id, slug, hash_algo, file_hash, pre_hash, file_size, mime_type, storage_path, status, created_at
`

type CreatePhysicalFileParams struct {
	Slug        string `json:"slug"`
	HashAlgo    string `json:"hashAlgo"`
	FileHash    string `json:"fileHash"`
	PreHash     string `json:"preHash"`
	FileSize    int64  `json:"fileSize"`
	MimeType    string `json:"mimeType"`
	StoragePath string `json:"storagePath"`
	Status      string `json:"status"`
}

func (q *Queries) CreatePhysicalFile(ctx context.Context, arg CreatePhysicalFileParams) (PhysicalFile, error) {
	row := q.db.QueryRow(ctx, createPhysicalFile,
		arg.Slug,
		arg.HashAlgo,
		arg.FileHash,
		arg.PreHash,
		arg.FileSize,
		arg.MimeType,
		arg.StoragePath,
		arg.Status,
	)
	var i PhysicalFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deletePhysicalFile = `-- name: DeletePhysicalFile :exec
DELETE FROM physical_files WHERE id = $1
`

func (q *Queries) DeletePhysicalFile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePhysicalFile, id)
	return err
}

const getPhysicalFileByHash = `-- name: GetPhysicalFileByHash :one
SELECT id, slug, hash_algo, file_hash, pre_hash, file_size, mime_type, storage_path, status, created_at FROM physical_files
WHERE hash_algo = $1 AND file_hash = $2 AND status = 'completed'
LIMIT 1
`

type GetPhysicalFileByHashParams struct {
	HashAlgo string `json:"hashAlgo"`
	FileHash string `json:"fileHash"`
}

func (q *Queries) GetPhysicalFileByHash(ctx context.Context, arg GetPhysicalFileByHashParams) (PhysicalFile, error) {
	row := q.db.QueryRow(ctx, getPhysicalFileByHash, arg.HashAlgo, arg.FileHash)
	var i PhysicalFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPhysicalFileByID = `-- name: GetPhysicalFileByID :one
SELECT id, slug, hash_algo, file_hash, pre_hash, file_size, mime_type, storage_path, status, created_at FROM physical_files WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPhysicalFileByID(ctx context.Context, id int64) (PhysicalFile, error) {
	row := q.db.QueryRow(ctx, getPhysicalFileByID, id)
	var i PhysicalFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPhysicalFileByPreHash = `-- name: GetPhysicalFileByPreHash :one
SELECT id, slug, hash_algo, file_hash, pre_hash, file_size, mime_type, storage_path, status, created_at FROM physical_files
WHERE file_size = $1 AND pre_hash = $2 AND status = 'completed'
LIMIT 1
`

type GetPhysicalFileByPreHashParams struct {
	FileSize int64  `json:"fileSize"`
	PreHash  string `json:"preHash"`
}

func (q *Queries) GetPhysicalFileByPreHash(ctx context.Context, arg GetPhysicalFileByPreHashParams) (PhysicalFile, error) {
	row := q.db.QueryRow(ctx, getPhysicalFileByPreHash, arg.FileSize, arg.PreHash)
	var i PhysicalFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPhysicalFileBySlug = `-- name: GetPhysicalFileBySlug :one
SELECT id, slug, hash_algo, file_hash, pre_hash, file_size, mime_type, storage_path, status, created_at FROM physical_files WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetPhysicalFileBySlug(ctx context.Context, slug string) (PhysicalFile, error) {
	row := q.db.QueryRow(ctx, getPhysicalFileBySlug, slug)
	var i PhysicalFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
