// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: physical_files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPhysicalFiles = `-- name: CountPhysicalFiles :one
SELECT COUNT(*) FROM physical_files pf
WHERE ($1::text IS NULL OR pf.status = $1)
  AND ($2::text IS NULL
       OR pf.slug ILIKE '%' || $2::text || '%'
       OR pf.file_hash ILIKE '%' || $2::text || '%'
       OR pf.storage_path ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL
       OR pf.file_hash ILIKE '%' || $3::text || '%')
  AND ($4::text IS NULL
       OR pf.mime_type ILIKE '%' || $4::text || '%')
  AND ($5::bigint IS NULL OR pf.file_size >= $5::bigint)
  AND ($6::bigint IS NULL OR pf.file_size <= $6::bigint)
  AND ($7::timestamptz IS NULL
       OR pf.created_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL
       OR pf.created_at <= $8::timestamptz)
`

type CountPhysicalFilesParams struct {
	Status      pgtype.Text        `json:"status"`
	Search      pgtype.Text        `json:"search"`
	HashFilter  pgtype.Text        `json:"hashFilter"`
	MimeFilter  pgtype.Text        `json:"mimeFilter"`
	MinSize     pgtype.Int8        `json:"minSize"`
	MaxSize     pgtype.Int8        `json:"maxSize"`
	CreatedFrom pgtype.Timestamptz `json:"createdFrom"`
	CreatedTo   pgtype.Timestamptz `json:"createdTo"`
}

func (q *Queries) CountPhysicalFiles(ctx context.Context, arg CountPhysicalFilesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPhysicalFiles,
		arg.Status,
		arg.Search,
		arg.HashFilter,
		arg.MimeFilter,
		arg.MinSize,
		arg.MaxSize,
		arg.CreatedFrom,
		arg.CreatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReferencesByFileID = `-- name: CountReferencesByFileID :one
SELECT
    (SELECT COUNT(*) FROM user_files uf WHERE uf.physical_file_id = $1)
    +
    (SELECT COUNT(*) FROM media_items mi WHERE mi.physical_file_id = $1)
`

func (q *Queries) CountReferencesByFileID(ctx context.Context, physicalFileID pgtype.Int8) (int32, error) {
	row := q.db.QueryRow(ctx, countReferencesByFileID, physicalFileID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createPhysicalFile = `-- name: CreatePhysicalFile :one
INSERT INTO physical_files (slug, hash_algo, file_hash, pre_hash, file_size, mime_type, storage_path, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (hash_algo, file_hash) DO NOTHING
RETURNING id, slug, hash_algo, file_hash, pre_hash, file_size, mime_type, storage_path, status, created_at
`

type CreatePhysicalFileParams struct {
	Slug        string `json:"slug"`
	HashAlgo    string `json:"hashAlgo"`
	FileHash    string `json:"fileHash"`
	PreHash     string `json:"preHash"`
	FileSize    int64  `json:"fileSize"`
	MimeType    string `json:"mimeType"`
	StoragePath string `json:"storagePath"`
	Status      string `json:"status"`
}

func (q *Queries) CreatePhysicalFile(ctx context.Context, arg CreatePhysicalFileParams) (PhysicalFile, error) {
	row := q.db.QueryRow(ctx, createPhysicalFile,
		arg.Slug,
		arg.HashAlgo,
		arg.FileHash,
		arg.PreHash,
		arg.FileSize,
		arg.MimeType,
		arg.StoragePath,
		arg.Status,
	)
	var i PhysicalFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deletePhysicalFile = `-- name: DeletePhysicalFile :exec
DELETE FROM physical_files WHERE id = $1
`

func (q *Queries) DeletePhysicalFile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePhysicalFile, id)
	return err
}

const getPhysicalFileByHash = `-- name: GetPhysicalFileByHash :one
SELECT id, slug, hash_algo, file_hash, pre_hash, file_size, mime_type, storage_path, status, created_at FROM physical_files
WHERE hash_algo = $1 AND file_hash = $2 AND status = 'completed'
LIMIT 1
`

type GetPhysicalFileByHashParams struct {
	HashAlgo string `json:"hashAlgo"`
	FileHash string `json:"fileHash"`
}

func (q *Queries) GetPhysicalFileByHash(ctx context.Context, arg GetPhysicalFileByHashParams) (PhysicalFile, error) {
	row := q.db.QueryRow(ctx, getPhysicalFileByHash, arg.HashAlgo, arg.FileHash)
	var i PhysicalFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPhysicalFileByID = `-- name: GetPhysicalFileByID :one
SELECT id, slug, hash_algo, file_hash, pre_hash, file_size, mime_type, storage_path, status, created_at FROM physical_files WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPhysicalFileByID(ctx context.Context, id int64) (PhysicalFile, error) {
	row := q.db.QueryRow(ctx, getPhysicalFileByID, id)
	var i PhysicalFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPhysicalFileByPreHash = `-- name: GetPhysicalFileByPreHash :one
SELECT id, slug, hash_algo, file_hash, pre_hash, file_size, mime_type, storage_path, status, created_at FROM physical_files
WHERE file_size = $1 AND pre_hash = $2 AND status = 'completed'
LIMIT 1
`

type GetPhysicalFileByPreHashParams struct {
	FileSize int64  `json:"fileSize"`
	PreHash  string `json:"preHash"`
}

func (q *Queries) GetPhysicalFileByPreHash(ctx context.Context, arg GetPhysicalFileByPreHashParams) (PhysicalFile, error) {
	row := q.db.QueryRow(ctx, getPhysicalFileByPreHash, arg.FileSize, arg.PreHash)
	var i PhysicalFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPhysicalFileBySlug = `-- name: GetPhysicalFileBySlug :one
SELECT id, slug, hash_algo, file_hash, pre_hash, file_size, mime_type, storage_path, status, created_at FROM physical_files WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetPhysicalFileBySlug(ctx context.Context, slug string) (PhysicalFile, error) {
	row := q.db.QueryRow(ctx, getPhysicalFileBySlug, slug)
	var i PhysicalFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPhysicalFiles = `-- name: ListPhysicalFiles :many
SELECT pf.id, pf.slug, pf.hash_algo, pf.file_hash, pf.pre_hash, pf.file_size, pf.mime_type, pf.storage_path, pf.status, pf.created_at,
    (SELECT COUNT(*) FROM user_files uf WHERE uf.physical_file_id = pf.id) AS user_file_count,
    (SELECT COUNT(*) FROM media_items mi WHERE mi.physical_file_id = pf.id) AS media_item_count
FROM physical_files pf
WHERE ($1::text IS NULL OR pf.status = $1)
  AND ($2::text IS NULL
       OR pf.slug ILIKE '%' || $2::text || '%'
       OR pf.file_hash ILIKE '%' || $2::text || '%'
       OR pf.storage_path ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL
       OR pf.file_hash ILIKE '%' || $3::text || '%')
  AND ($4::text IS NULL
       OR pf.mime_type ILIKE '%' || $4::text || '%')
  AND ($5::bigint IS NULL OR pf.file_size >= $5::bigint)
  AND ($6::bigint IS NULL OR pf.file_size <= $6::bigint)
  AND ($7::timestamptz IS NULL
       OR pf.created_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL
       OR pf.created_at <= $8::timestamptz)
ORDER BY pf.created_at DESC
LIMIT $10
OFFSET $9
`

type ListPhysicalFilesParams struct {
	Status      pgtype.Text        `json:"status"`
	Search      pgtype.Text        `json:"search"`
	HashFilter  pgtype.Text        `json:"hashFilter"`
	MimeFilter  pgtype.Text        `json:"mimeFilter"`
	MinSize     pgtype.Int8        `json:"minSize"`
	MaxSize     pgtype.Int8        `json:"maxSize"`
	CreatedFrom pgtype.Timestamptz `json:"createdFrom"`
	CreatedTo   pgtype.Timestamptz `json:"createdTo"`
	Off         int32              `json:"off"`
	Lim         int32              `json:"lim"`
}

type ListPhysicalFilesRow struct {
	ID             int64              `json:"id"`
	Slug           string             `json:"slug"`
	HashAlgo       string             `json:"hashAlgo"`
	FileHash       string             `json:"fileHash"`
	PreHash        string             `json:"preHash"`
	FileSize       int64              `json:"fileSize"`
	MimeType       string             `json:"mimeType"`
	StoragePath    string             `json:"storagePath"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UserFileCount  int64              `json:"userFileCount"`
	MediaItemCount int64              `json:"mediaItemCount"`
}

func (q *Queries) ListPhysicalFiles(ctx context.Context, arg ListPhysicalFilesParams) ([]ListPhysicalFilesRow, error) {
	rows, err := q.db.Query(ctx, listPhysicalFiles,
		arg.Status,
		arg.Search,
		arg.HashFilter,
		arg.MimeFilter,
		arg.MinSize,
		arg.MaxSize,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPhysicalFilesRow
	for rows.Next() {
		var i ListPhysicalFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.HashAlgo,
			&i.FileHash,
			&i.PreHash,
			&i.FileSize,
			&i.MimeType,
			&i.StoragePath,
			&i.Status,
			&i.CreatedAt,
			&i.UserFileCount,
			&i.MediaItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
