// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AtomicIncrementStorage(ctx context.Context, arg AtomicIncrementStorageParams) (AtomicIncrementStorageRow, error)
	CheckNameConflict(ctx context.Context, arg CheckNameConflictParams) (CheckNameConflictRow, error)
	CountFilesByParent(ctx context.Context, arg CountFilesByParentParams) (int64, error)
	CountMediaItemsByUser(ctx context.Context, userID int64) (int64, error)
	CountReferencesByFileID(ctx context.Context, physicalFileID pgtype.Int8) (int64, error)
	CountStarredFiles(ctx context.Context, userID int64) (int64, error)
	CountTransactionsByUser(ctx context.Context, userID int64) (int64, error)
	CountTrashedFiles(ctx context.Context, userID int64) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (UserFile, error)
	CreateLevel(ctx context.Context, arg CreateLevelParams) (UserLevel, error)
	CreateMediaItem(ctx context.Context, arg CreateMediaItemParams) (MediaItem, error)
	CreateMediaJob(ctx context.Context, arg CreateMediaJobParams) (MediaJob, error)
	CreatePhysicalFile(ctx context.Context, arg CreatePhysicalFileParams) (PhysicalFile, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (UserProfile, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateStorageStats(ctx context.Context, arg CreateStorageStatsParams) (UserStorageStat, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (UserTransaction, error)
	CreateTranscode(ctx context.Context, arg CreateTranscodeParams) (MediaTranscode, error)
	CreateUploadTask(ctx context.Context, arg CreateUploadTaskParams) (UploadTask, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredTasks(ctx context.Context) error
	DeleteFile(ctx context.Context, id int64) error
	DeleteMediaItem(ctx context.Context, id int64) error
	DeletePhysicalFile(ctx context.Context, id int64) error
	GetAncestors(ctx context.Context, id int64) ([]GetAncestorsRow, error)
	GetFileByID(ctx context.Context, id int64) (UserFile, error)
	GetFileBySlug(ctx context.Context, slug string) (UserFile, error)
	GetFileBySlugForUser(ctx context.Context, arg GetFileBySlugForUserParams) (UserFile, error)
	GetJobBySlug(ctx context.Context, slug string) (MediaJob, error)
	GetLevelByUserID(ctx context.Context, userID int64) (UserLevel, error)
	GetMediaItemBySlug(ctx context.Context, slug string) (GetMediaItemBySlugRow, error)
	GetMediaItemByUserAndFile(ctx context.Context, arg GetMediaItemByUserAndFileParams) (MediaItem, error)
	GetPendingJobs(ctx context.Context, limit int32) ([]MediaJob, error)
	GetPhysicalFileByHash(ctx context.Context, arg GetPhysicalFileByHashParams) (PhysicalFile, error)
	GetPhysicalFileByID(ctx context.Context, id int64) (PhysicalFile, error)
	GetPhysicalFileByPreHash(ctx context.Context, arg GetPhysicalFileByPreHashParams) (PhysicalFile, error)
	GetPhysicalFileBySlug(ctx context.Context, slug string) (PhysicalFile, error)
	GetProfileByUserID(ctx context.Context, userID int64) (UserProfile, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetStorageStats(ctx context.Context, userID int64) (UserStorageStat, error)
	GetTranscodeByID(ctx context.Context, id int64) (MediaTranscode, error)
	GetTranscodeByPhysicalFileAndProfile(ctx context.Context, arg GetTranscodeByPhysicalFileAndProfileParams) (MediaTranscode, error)
	GetTranscodeBySlug(ctx context.Context, slug string) (MediaTranscode, error)
	GetUploadTaskByHashForUser(ctx context.Context, arg GetUploadTaskByHashForUserParams) (UploadTask, error)
	GetUploadTaskBySlug(ctx context.Context, slug string) (UploadTask, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserBySlug(ctx context.Context, slug string) (User, error)
	ListFilesByParent(ctx context.Context, arg ListFilesByParentParams) ([]UserFile, error)
	ListMediaItemsByUser(ctx context.Context, arg ListMediaItemsByUserParams) ([]ListMediaItemsByUserRow, error)
	ListStarredFiles(ctx context.Context, arg ListStarredFilesParams) ([]UserFile, error)
	ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]UserTransaction, error)
	ListTrashedFiles(ctx context.Context, arg ListTrashedFilesParams) ([]UserFile, error)
	MoveFile(ctx context.Context, arg MoveFileParams) error
	RenameFile(ctx context.Context, arg RenameFileParams) error
	RestoreFile(ctx context.Context, id int64) error
	RevokeAllForUser(ctx context.Context, userID int64) error
	RevokeRefreshToken(ctx context.Context, id int64) error
	SetStarred(ctx context.Context, arg SetStarredParams) error
	SetTrashed(ctx context.Context, arg SetTrashedParams) error
	UpdateAvatarPath(ctx context.Context, arg UpdateAvatarPathParams) error
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) error
	UpdateTranscodeHLS(ctx context.Context, arg UpdateTranscodeHLSParams) error
	UpdateTranscodeStatus(ctx context.Context, arg UpdateTranscodeStatusParams) error
	UpdateUploadTaskPhysicalFile(ctx context.Context, arg UpdateUploadTaskPhysicalFileParams) error
	UpdateUploadTaskStatus(ctx context.Context, arg UpdateUploadTaskStatusParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
