// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddPhotoToAlbum(ctx context.Context, arg AddPhotoToAlbumParams) (PhotoAlbumItem, error)
	AtomicIncrementStorage(ctx context.Context, arg AtomicIncrementStorageParams) (AtomicIncrementStorageRow, error)
	CheckNameConflict(ctx context.Context, arg CheckNameConflictParams) (CheckNameConflictRow, error)
	CountActivityLogsByUser(ctx context.Context, userID int64) (int64, error)
	CountImageFiles(ctx context.Context, userID int64) (int64, error)
	CountMediaItemsByUser(ctx context.Context, userID int64) (int64, error)
	CountPhotoAlbumItems(ctx context.Context, albumID int64) (int64, error)
	CountPhotoAlbumsByUser(ctx context.Context, userID int64) (int64, error)
	CountPhysicalFiles(ctx context.Context, arg CountPhysicalFilesParams) (int64, error)
	CountReferencesByFileID(ctx context.Context, physicalFileID pgtype.Int8) (int32, error)
	CountSecurityLogsByUser(ctx context.Context, userID int64) (int64, error)
	CountTransactionsByUser(ctx context.Context, userID int64) (int64, error)
	CountUploadTasksByUser(ctx context.Context, arg CountUploadTasksByUserParams) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error
	CreateFile(ctx context.Context, arg CreateFileParams) (UserFile, error)
	CreateLevel(ctx context.Context, arg CreateLevelParams) (UserLevel, error)
	CreateMediaItem(ctx context.Context, arg CreateMediaItemParams) (MediaItem, error)
	CreateMediaJob(ctx context.Context, arg CreateMediaJobParams) (MediaJob, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (CreateOAuthAccountRow, error)
	CreatePhotoAlbum(ctx context.Context, arg CreatePhotoAlbumParams) (PhotoAlbum, error)
	CreatePhysicalFile(ctx context.Context, arg CreatePhysicalFileParams) (PhysicalFile, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (UserProfile, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateStorageStats(ctx context.Context, arg CreateStorageStatsParams) (UserStorageStat, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (UserTransaction, error)
	CreateTranscode(ctx context.Context, arg CreateTranscodeParams) (MediaTranscode, error)
	CreateUploadTask(ctx context.Context, arg CreateUploadTaskParams) (UploadTask, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementPhotoAlbumItemCount(ctx context.Context, id int64) error
	DeleteExpiredTasks(ctx context.Context) error
	DeleteFile(ctx context.Context, id int64) error
	DeleteMediaItem(ctx context.Context, id int64) error
	DeletePhotoAlbum(ctx context.Context, arg DeletePhotoAlbumParams) error
	DeletePhysicalFile(ctx context.Context, id int64) error
	DeleteUploadTaskBySlug(ctx context.Context, arg DeleteUploadTaskBySlugParams) error
	DeleteUploadTasksBySlugs(ctx context.Context, arg DeleteUploadTasksBySlugsParams) error
	GetActiveFileByMediaUploadIdentity(ctx context.Context, arg GetActiveFileByMediaUploadIdentityParams) (UserFile, error)
	GetAncestors(ctx context.Context, id int64) ([]GetAncestorsRow, error)
	GetExpiredTrashedFiles(ctx context.Context) ([]GetExpiredTrashedFilesRow, error)
	GetFileByID(ctx context.Context, id int64) (UserFile, error)
	GetFileBySlug(ctx context.Context, slug string) (UserFile, error)
	GetFileBySlugForUser(ctx context.Context, arg GetFileBySlugForUserParams) (UserFile, error)
	GetJobBySlug(ctx context.Context, slug string) (MediaJob, error)
	GetLevelByUserID(ctx context.Context, userID int64) (UserLevel, error)
	GetMediaItemBySlug(ctx context.Context, slug string) (GetMediaItemBySlugRow, error)
	GetMediaItemByTranscodeID(ctx context.Context, transcodeID pgtype.Int8) (MediaItem, error)
	GetMediaItemByUserAndFile(ctx context.Context, arg GetMediaItemByUserAndFileParams) (MediaItem, error)
	GetOAuthAccountByProviderAndID(ctx context.Context, arg GetOAuthAccountByProviderAndIDParams) (GetOAuthAccountByProviderAndIDRow, error)
	GetOAuthAccountsByUserID(ctx context.Context, userID int64) ([]GetOAuthAccountsByUserIDRow, error)
	GetPendingJobs(ctx context.Context, limit int32) ([]MediaJob, error)
	GetPhotoAlbumBySlug(ctx context.Context, arg GetPhotoAlbumBySlugParams) (PhotoAlbum, error)
	GetPhotoAlbumItem(ctx context.Context, arg GetPhotoAlbumItemParams) (GetPhotoAlbumItemRow, error)
	GetPhotoAlbumItemCountByFile(ctx context.Context, fileSlug string) (int64, error)
	GetPhysicalFileByHash(ctx context.Context, arg GetPhysicalFileByHashParams) (PhysicalFile, error)
	GetPhysicalFileByID(ctx context.Context, id int64) (PhysicalFile, error)
	GetPhysicalFileByPreHash(ctx context.Context, arg GetPhysicalFileByPreHashParams) (PhysicalFile, error)
	GetPhysicalFileBySlug(ctx context.Context, slug string) (PhysicalFile, error)
	GetProfileByUserID(ctx context.Context, userID int64) (UserProfile, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetStorageStats(ctx context.Context, userID int64) (UserStorageStat, error)
	GetSystemDirByKind(ctx context.Context, arg GetSystemDirByKindParams) (UserFile, error)
	GetTranscodeByID(ctx context.Context, id int64) (MediaTranscode, error)
	GetTranscodeByPhysicalFileAndProfile(ctx context.Context, arg GetTranscodeByPhysicalFileAndProfileParams) (MediaTranscode, error)
	GetTranscodeBySlug(ctx context.Context, slug string) (MediaTranscode, error)
	GetUploadTaskByHashForUser(ctx context.Context, arg GetUploadTaskByHashForUserParams) (UploadTask, error)
	GetUploadTaskBySlug(ctx context.Context, slug string) (UploadTask, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserBySlug(ctx context.Context, slug string) (User, error)
	GetUserFilesByPhysicalFileID(ctx context.Context, arg GetUserFilesByPhysicalFileIDParams) ([]GetUserFilesByPhysicalFileIDRow, error)
	IncrementPhotoAlbumItemCount(ctx context.Context, id int64) error
	ListActivityLogsByUser(ctx context.Context, arg ListActivityLogsByUserParams) ([]UserActivityLog, error)
	ListImageFiles(ctx context.Context, arg ListImageFilesParams) ([]ListImageFilesRow, error)
	ListMediaItemsByUser(ctx context.Context, arg ListMediaItemsByUserParams) ([]ListMediaItemsByUserRow, error)
	ListPhotoAlbumItems(ctx context.Context, arg ListPhotoAlbumItemsParams) ([]ListPhotoAlbumItemsRow, error)
	ListPhotoAlbumsByFile(ctx context.Context, arg ListPhotoAlbumsByFileParams) ([]PhotoAlbum, error)
	ListPhotoAlbumsByUser(ctx context.Context, arg ListPhotoAlbumsByUserParams) ([]PhotoAlbum, error)
	ListPhysicalFiles(ctx context.Context, arg ListPhysicalFilesParams) ([]ListPhysicalFilesRow, error)
	ListSecurityLogsByUser(ctx context.Context, arg ListSecurityLogsByUserParams) ([]UserActivityLog, error)
	ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]UserTransaction, error)
	ListUploadTasksByUser(ctx context.Context, arg ListUploadTasksByUserParams) ([]UploadTask, error)
	MoveFile(ctx context.Context, arg MoveFileParams) error
	RemovePhotoFromAlbum(ctx context.Context, arg RemovePhotoFromAlbumParams) error
	RenameFile(ctx context.Context, arg RenameFileParams) error
	RestoreFile(ctx context.Context, id int64) error
	RevokeAllForUser(ctx context.Context, userID int64) error
	RevokeRefreshToken(ctx context.Context, id int64) error
	SetStarred(ctx context.Context, arg SetStarredParams) error
	SetTrashed(ctx context.Context, arg SetTrashedParams) error
	UpdateAvatarPath(ctx context.Context, arg UpdateAvatarPathParams) error
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error
	UpdateMediaItemPoster(ctx context.Context, arg UpdateMediaItemPosterParams) error
	UpdatePhotoAlbum(ctx context.Context, arg UpdatePhotoAlbumParams) (PhotoAlbum, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) error
	UpdateTranscodeHLS(ctx context.Context, arg UpdateTranscodeHLSParams) error
	UpdateTranscodeStatus(ctx context.Context, arg UpdateTranscodeStatusParams) error
	UpdateUploadTaskFileHash(ctx context.Context, arg UpdateUploadTaskFileHashParams) error
	UpdateUploadTaskPhysicalFile(ctx context.Context, arg UpdateUploadTaskPhysicalFileParams) error
	UpdateUploadTaskPreHash(ctx context.Context, arg UpdateUploadTaskPreHashParams) error
	UpdateUploadTaskStatus(ctx context.Context, arg UpdateUploadTaskStatusParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
