// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload_tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUploadTasksByUser = `-- name: CountUploadTasksByUser :one
SELECT COUNT(*) FROM upload_tasks
WHERE owner_user_id = $1
  AND ($2::timestamptz IS NULL OR created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR created_at <= $3::timestamptz)
  AND ($4::varchar IS NULL OR status = $4::varchar)
`

type CountUploadTasksByUserParams struct {
	OwnerUserID int64              `json:"ownerUserId"`
	StartDate   pgtype.Timestamptz `json:"startDate"`
	EndDate     pgtype.Timestamptz `json:"endDate"`
	Status      pgtype.Text        `json:"status"`
}

func (q *Queries) CountUploadTasksByUser(ctx context.Context, arg CountUploadTasksByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUploadTasksByUser,
		arg.OwnerUserID,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUploadTask = `-- name: CreateUploadTask :one
INSERT INTO upload_tasks (slug, owner_user_id, hash_algo, file_hash, pre_hash, file_size, mime_type, original_name, total_chunks, chunk_size, status, expires_at, parent_slug)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, slug, owner_user_id, hash_algo, file_hash, pre_hash, file_size, mime_type, total_chunks, chunk_size, status, physical_file_id, error_msg, expires_at, created_at, updated_at, original_name, parent_slug, task_type, source_url, received_bytes
`

type CreateUploadTaskParams struct {
	Slug         string             `json:"slug"`
	OwnerUserID  int64              `json:"ownerUserId"`
	HashAlgo     string             `json:"hashAlgo"`
	FileHash     string             `json:"fileHash"`
	PreHash      string             `json:"preHash"`
	FileSize     int64              `json:"fileSize"`
	MimeType     string             `json:"mimeType"`
	OriginalName string             `json:"originalName"`
	TotalChunks  int32              `json:"totalChunks"`
	ChunkSize    int32              `json:"chunkSize"`
	Status       string             `json:"status"`
	ExpiresAt    pgtype.Timestamptz `json:"expiresAt"`
	ParentSlug   pgtype.Text        `json:"parentSlug"`
}

func (q *Queries) CreateUploadTask(ctx context.Context, arg CreateUploadTaskParams) (UploadTask, error) {
	row := q.db.QueryRow(ctx, createUploadTask,
		arg.Slug,
		arg.OwnerUserID,
		arg.HashAlgo,
		arg.FileHash,
		arg.PreHash,
		arg.FileSize,
		arg.MimeType,
		arg.OriginalName,
		arg.TotalChunks,
		arg.ChunkSize,
		arg.Status,
		arg.ExpiresAt,
		arg.ParentSlug,
	)
	var i UploadTask
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerUserID,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.TotalChunks,
		&i.ChunkSize,
		&i.Status,
		&i.PhysicalFileID,
		&i.ErrorMsg,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalName,
		&i.ParentSlug,
		&i.TaskType,
		&i.SourceUrl,
		&i.ReceivedBytes,
	)
	return i, err
}

const deleteExpiredTasks = `-- name: DeleteExpiredTasks :exec
DELETE FROM upload_tasks
WHERE expires_at < NOW() AND status IN ('created', 'uploading', 'merging')
`

func (q *Queries) DeleteExpiredTasks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTasks)
	return err
}

const deleteUploadTaskBySlug = `-- name: DeleteUploadTaskBySlug :exec
DELETE FROM upload_tasks WHERE slug = $1 AND owner_user_id = $2
`

type DeleteUploadTaskBySlugParams struct {
	Slug        string `json:"slug"`
	OwnerUserID int64  `json:"ownerUserId"`
}

func (q *Queries) DeleteUploadTaskBySlug(ctx context.Context, arg DeleteUploadTaskBySlugParams) error {
	_, err := q.db.Exec(ctx, deleteUploadTaskBySlug, arg.Slug, arg.OwnerUserID)
	return err
}

const deleteUploadTasksBySlugs = `-- name: DeleteUploadTasksBySlugs :exec
DELETE FROM upload_tasks WHERE slug = ANY($1::varchar[]) AND owner_user_id = $2
`

type DeleteUploadTasksBySlugsParams struct {
	Column1     []string `json:"column1"`
	OwnerUserID int64    `json:"ownerUserId"`
}

func (q *Queries) DeleteUploadTasksBySlugs(ctx context.Context, arg DeleteUploadTasksBySlugsParams) error {
	_, err := q.db.Exec(ctx, deleteUploadTasksBySlugs, arg.Column1, arg.OwnerUserID)
	return err
}

const getUploadTaskByHashForUser = `-- name: GetUploadTaskByHashForUser :one
SELECT id, slug, owner_user_id, hash_algo, file_hash, pre_hash, file_size, mime_type, total_chunks, chunk_size, status, physical_file_id, error_msg, expires_at, created_at, updated_at, original_name, parent_slug, task_type, source_url, received_bytes FROM upload_tasks
WHERE owner_user_id = $1 AND file_hash = $2 AND status IN ('created', 'uploading')
LIMIT 1
`

type GetUploadTaskByHashForUserParams struct {
	OwnerUserID int64  `json:"ownerUserId"`
	FileHash    string `json:"fileHash"`
}

func (q *Queries) GetUploadTaskByHashForUser(ctx context.Context, arg GetUploadTaskByHashForUserParams) (UploadTask, error) {
	row := q.db.QueryRow(ctx, getUploadTaskByHashForUser, arg.OwnerUserID, arg.FileHash)
	var i UploadTask
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerUserID,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.TotalChunks,
		&i.ChunkSize,
		&i.Status,
		&i.PhysicalFileID,
		&i.ErrorMsg,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalName,
		&i.ParentSlug,
		&i.TaskType,
		&i.SourceUrl,
		&i.ReceivedBytes,
	)
	return i, err
}

const getUploadTaskBySlug = `-- name: GetUploadTaskBySlug :one
SELECT id, slug, owner_user_id, hash_algo, file_hash, pre_hash, file_size, mime_type, total_chunks, chunk_size, status, physical_file_id, error_msg, expires_at, created_at, updated_at, original_name, parent_slug, task_type, source_url, received_bytes FROM upload_tasks WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetUploadTaskBySlug(ctx context.Context, slug string) (UploadTask, error) {
	row := q.db.QueryRow(ctx, getUploadTaskBySlug, slug)
	var i UploadTask
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerUserID,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.TotalChunks,
		&i.ChunkSize,
		&i.Status,
		&i.PhysicalFileID,
		&i.ErrorMsg,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalName,
		&i.ParentSlug,
		&i.TaskType,
		&i.SourceUrl,
		&i.ReceivedBytes,
	)
	return i, err
}

const listUploadTasksByUser = `-- name: ListUploadTasksByUser :many
SELECT id, slug, owner_user_id, hash_algo, file_hash, pre_hash, file_size, mime_type, total_chunks, chunk_size, status, physical_file_id, error_msg, expires_at, created_at, updated_at, original_name, parent_slug, task_type, source_url, received_bytes FROM upload_tasks
WHERE owner_user_id = $1
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at <= $5::timestamptz)
  AND ($6::varchar IS NULL OR status = $6::varchar)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUploadTasksByUserParams struct {
	OwnerUserID int64              `json:"ownerUserId"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
	StartDate   pgtype.Timestamptz `json:"startDate"`
	EndDate     pgtype.Timestamptz `json:"endDate"`
	Status      pgtype.Text        `json:"status"`
}

func (q *Queries) ListUploadTasksByUser(ctx context.Context, arg ListUploadTasksByUserParams) ([]UploadTask, error) {
	rows, err := q.db.Query(ctx, listUploadTasksByUser,
		arg.OwnerUserID,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadTask
	for rows.Next() {
		var i UploadTask
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.OwnerUserID,
			&i.HashAlgo,
			&i.FileHash,
			&i.PreHash,
			&i.FileSize,
			&i.MimeType,
			&i.TotalChunks,
			&i.ChunkSize,
			&i.Status,
			&i.PhysicalFileID,
			&i.ErrorMsg,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalName,
			&i.ParentSlug,
			&i.TaskType,
			&i.SourceUrl,
			&i.ReceivedBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUploadTaskFileHash = `-- name: UpdateUploadTaskFileHash :exec
UPDATE upload_tasks
SET file_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUploadTaskFileHashParams struct {
	ID       int64  `json:"id"`
	FileHash string `json:"fileHash"`
}

func (q *Queries) UpdateUploadTaskFileHash(ctx context.Context, arg UpdateUploadTaskFileHashParams) error {
	_, err := q.db.Exec(ctx, updateUploadTaskFileHash, arg.ID, arg.FileHash)
	return err
}

const updateUploadTaskPhysicalFile = `-- name: UpdateUploadTaskPhysicalFile :exec
UPDATE upload_tasks
SET physical_file_id = $2, status = 'done', updated_at = NOW()
WHERE id = $1
`

type UpdateUploadTaskPhysicalFileParams struct {
	ID             int64       `json:"id"`
	PhysicalFileID pgtype.Int8 `json:"physicalFileId"`
}

func (q *Queries) UpdateUploadTaskPhysicalFile(ctx context.Context, arg UpdateUploadTaskPhysicalFileParams) error {
	_, err := q.db.Exec(ctx, updateUploadTaskPhysicalFile, arg.ID, arg.PhysicalFileID)
	return err
}

const updateUploadTaskPreHash = `-- name: UpdateUploadTaskPreHash :exec
UPDATE upload_tasks
SET pre_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUploadTaskPreHashParams struct {
	ID      int64  `json:"id"`
	PreHash string `json:"preHash"`
}

func (q *Queries) UpdateUploadTaskPreHash(ctx context.Context, arg UpdateUploadTaskPreHashParams) error {
	_, err := q.db.Exec(ctx, updateUploadTaskPreHash, arg.ID, arg.PreHash)
	return err
}

const updateUploadTaskStatus = `-- name: UpdateUploadTaskStatus :exec
UPDATE upload_tasks
SET status = $2, error_msg = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateUploadTaskStatusParams struct {
	ID       int64       `json:"id"`
	Status   string      `json:"status"`
	ErrorMsg pgtype.Text `json:"errorMsg"`
}

func (q *Queries) UpdateUploadTaskStatus(ctx context.Context, arg UpdateUploadTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateUploadTaskStatus, arg.ID, arg.Status, arg.ErrorMsg)
	return err
}
