// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: upload_tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUploadTask = `-- name: CreateUploadTask :one
INSERT INTO upload_tasks (slug, owner_user_id, hash_algo, file_hash, pre_hash, file_size, mime_type, total_chunks, chunk_size, status, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, slug, owner_user_id, hash_algo, file_hash, pre_hash, file_size, mime_type, total_chunks, chunk_size, status, physical_file_id, error_msg, expires_at, created_at, updated_at
`

type CreateUploadTaskParams struct {
	Slug        string             `json:"slug"`
	OwnerUserID int64              `json:"owner_user_id"`
	HashAlgo    string             `json:"hash_algo"`
	FileHash    string             `json:"file_hash"`
	PreHash     string             `json:"pre_hash"`
	FileSize    int64              `json:"file_size"`
	MimeType    string             `json:"mime_type"`
	TotalChunks int32              `json:"total_chunks"`
	ChunkSize   int32              `json:"chunk_size"`
	Status      string             `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUploadTask(ctx context.Context, arg CreateUploadTaskParams) (UploadTask, error) {
	row := q.db.QueryRow(ctx, createUploadTask,
		arg.Slug,
		arg.OwnerUserID,
		arg.HashAlgo,
		arg.FileHash,
		arg.PreHash,
		arg.FileSize,
		arg.MimeType,
		arg.TotalChunks,
		arg.ChunkSize,
		arg.Status,
		arg.ExpiresAt,
	)
	var i UploadTask
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerUserID,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.TotalChunks,
		&i.ChunkSize,
		&i.Status,
		&i.PhysicalFileID,
		&i.ErrorMsg,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredTasks = `-- name: DeleteExpiredTasks :exec
DELETE FROM upload_tasks
WHERE expires_at < NOW() AND status IN ('created', 'uploading', 'merging')
`

func (q *Queries) DeleteExpiredTasks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTasks)
	return err
}

const getUploadTaskByHashForUser = `-- name: GetUploadTaskByHashForUser :one
SELECT id, slug, owner_user_id, hash_algo, file_hash, pre_hash, file_size, mime_type, total_chunks, chunk_size, status, physical_file_id, error_msg, expires_at, created_at, updated_at FROM upload_tasks
WHERE owner_user_id = $1 AND file_hash = $2 AND status IN ('created', 'uploading')
LIMIT 1
`

type GetUploadTaskByHashForUserParams struct {
	OwnerUserID int64  `json:"owner_user_id"`
	FileHash    string `json:"file_hash"`
}

func (q *Queries) GetUploadTaskByHashForUser(ctx context.Context, arg GetUploadTaskByHashForUserParams) (UploadTask, error) {
	row := q.db.QueryRow(ctx, getUploadTaskByHashForUser, arg.OwnerUserID, arg.FileHash)
	var i UploadTask
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerUserID,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.TotalChunks,
		&i.ChunkSize,
		&i.Status,
		&i.PhysicalFileID,
		&i.ErrorMsg,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadTaskBySlug = `-- name: GetUploadTaskBySlug :one
SELECT id, slug, owner_user_id, hash_algo, file_hash, pre_hash, file_size, mime_type, total_chunks, chunk_size, status, physical_file_id, error_msg, expires_at, created_at, updated_at FROM upload_tasks WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetUploadTaskBySlug(ctx context.Context, slug string) (UploadTask, error) {
	row := q.db.QueryRow(ctx, getUploadTaskBySlug, slug)
	var i UploadTask
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OwnerUserID,
		&i.HashAlgo,
		&i.FileHash,
		&i.PreHash,
		&i.FileSize,
		&i.MimeType,
		&i.TotalChunks,
		&i.ChunkSize,
		&i.Status,
		&i.PhysicalFileID,
		&i.ErrorMsg,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUploadTaskPhysicalFile = `-- name: UpdateUploadTaskPhysicalFile :exec
UPDATE upload_tasks
SET physical_file_id = $2, status = 'done', updated_at = NOW()
WHERE id = $1
`

type UpdateUploadTaskPhysicalFileParams struct {
	ID             int64       `json:"id"`
	PhysicalFileID pgtype.Int8 `json:"physical_file_id"`
}

func (q *Queries) UpdateUploadTaskPhysicalFile(ctx context.Context, arg UpdateUploadTaskPhysicalFileParams) error {
	_, err := q.db.Exec(ctx, updateUploadTaskPhysicalFile, arg.ID, arg.PhysicalFileID)
	return err
}

const updateUploadTaskStatus = `-- name: UpdateUploadTaskStatus :exec
UPDATE upload_tasks
SET status = $2, error_msg = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateUploadTaskStatusParams struct {
	ID       int64       `json:"id"`
	Status   string      `json:"status"`
	ErrorMsg pgtype.Text `json:"error_msg"`
}

func (q *Queries) UpdateUploadTaskStatus(ctx context.Context, arg UpdateUploadTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateUploadTaskStatus, arg.ID, arg.Status, arg.ErrorMsg)
	return err
}
