// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO user_profiles (user_id, display_name)
VALUES ($1, $2)
RETURNING id, user_id, display_name, avatar_path, bio, created_at, updated_at
`

type CreateProfileParams struct {
	UserID      int64       `json:"user_id"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.UserID, arg.DisplayName)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.AvatarPath,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT id, user_id, display_name, avatar_path, bio, created_at, updated_at FROM user_profiles WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID int64) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.AvatarPath,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAvatarPath = `-- name: UpdateAvatarPath :exec
UPDATE user_profiles
SET avatar_path = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateAvatarPathParams struct {
	UserID     int64       `json:"user_id"`
	AvatarPath pgtype.Text `json:"avatar_path"`
}

func (q *Queries) UpdateAvatarPath(ctx context.Context, arg UpdateAvatarPathParams) error {
	_, err := q.db.Exec(ctx, updateAvatarPath, arg.UserID, arg.AvatarPath)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE user_profiles
SET display_name = $2, bio = $3, updated_at = NOW()
WHERE user_id = $1
`

type UpdateProfileParams struct {
	UserID      int64       `json:"user_id"`
	DisplayName pgtype.Text `json:"display_name"`
	Bio         pgtype.Text `json:"bio"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile, arg.UserID, arg.DisplayName, arg.Bio)
	return err
}
