// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkNameConflict = `-- name: CheckNameConflict :one
SELECT id, slug, file_name, is_dir, file_size FROM user_files
WHERE user_id = $1
  AND is_trashed = FALSE
  AND file_name = $2
  AND (
    ($3::bigint IS NULL AND parent_id IS NULL)
    OR
    ($3::bigint IS NOT NULL AND parent_id = $3::bigint)
  )
LIMIT 1
`

type CheckNameConflictParams struct {
	UserID   int64       `json:"user_id"`
	FileName string      `json:"file_name"`
	ParentID pgtype.Int8 `json:"parent_id"`
}

type CheckNameConflictRow struct {
	ID       int64  `json:"id"`
	Slug     string `json:"slug"`
	FileName string `json:"file_name"`
	IsDir    bool   `json:"is_dir"`
	FileSize int64  `json:"file_size"`
}

func (q *Queries) CheckNameConflict(ctx context.Context, arg CheckNameConflictParams) (CheckNameConflictRow, error) {
	row := q.db.QueryRow(ctx, checkNameConflict, arg.UserID, arg.FileName, arg.ParentID)
	var i CheckNameConflictRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.FileName,
		&i.IsDir,
		&i.FileSize,
	)
	return i, err
}

const countFilesByParent = `-- name: CountFilesByParent :one
SELECT COUNT(*) FROM user_files
WHERE user_id = $1
  AND is_trashed = FALSE
  AND (
    ($2::bigint IS NULL AND parent_id IS NULL)
    OR
    ($2::bigint IS NOT NULL AND parent_id = $2::bigint)
  )
`

type CountFilesByParentParams struct {
	UserID   int64       `json:"user_id"`
	ParentID pgtype.Int8 `json:"parent_id"`
}

func (q *Queries) CountFilesByParent(ctx context.Context, arg CountFilesByParentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesByParent, arg.UserID, arg.ParentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStarredFiles = `-- name: CountStarredFiles :one
SELECT COUNT(*) FROM user_files
WHERE user_id = $1 AND is_starred = TRUE AND is_trashed = FALSE
`

func (q *Queries) CountStarredFiles(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countStarredFiles, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrashedFiles = `-- name: CountTrashedFiles :one
SELECT COUNT(*) FROM user_files
WHERE user_id = $1 AND is_trashed = TRUE
`

func (q *Queries) CountTrashedFiles(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTrashedFiles, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO user_files (slug, user_id, physical_file_id, parent_id, file_name, is_dir, file_size, mime_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, slug, user_id, physical_file_id, parent_id, file_name, is_dir, file_size, mime_type, is_starred, is_trashed, trashed_at, created_at, updated_at
`

type CreateFileParams struct {
	Slug           string      `json:"slug"`
	UserID         int64       `json:"user_id"`
	PhysicalFileID pgtype.Int8 `json:"physical_file_id"`
	ParentID       pgtype.Int8 `json:"parent_id"`
	FileName       string      `json:"file_name"`
	IsDir          bool        `json:"is_dir"`
	FileSize       int64       `json:"file_size"`
	MimeType       pgtype.Text `json:"mime_type"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (UserFile, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.Slug,
		arg.UserID,
		arg.PhysicalFileID,
		arg.ParentID,
		arg.FileName,
		arg.IsDir,
		arg.FileSize,
		arg.MimeType,
	)
	var i UserFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.PhysicalFileID,
		&i.ParentID,
		&i.FileName,
		&i.IsDir,
		&i.FileSize,
		&i.MimeType,
		&i.IsStarred,
		&i.IsTrashed,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM user_files WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const getAncestors = `-- name: GetAncestors :many
WITH RECURSIVE ancestors AS (
    SELECT uf.id, uf.slug, uf.parent_id, uf.file_name, uf.is_dir
    FROM user_files uf WHERE uf.id = $1
    UNION ALL
    SELECT f.id, f.slug, f.parent_id, f.file_name, f.is_dir
    FROM user_files f
    JOIN ancestors a ON f.id = a.parent_id
)
SELECT a.id, a.slug, a.parent_id, a.file_name, a.is_dir FROM ancestors a ORDER BY a.id ASC
`

type GetAncestorsRow struct {
	ID       int64       `json:"id"`
	Slug     string      `json:"slug"`
	ParentID pgtype.Int8 `json:"parent_id"`
	FileName string      `json:"file_name"`
	IsDir    bool        `json:"is_dir"`
}

func (q *Queries) GetAncestors(ctx context.Context, id int64) ([]GetAncestorsRow, error) {
	rows, err := q.db.Query(ctx, getAncestors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAncestorsRow
	for rows.Next() {
		var i GetAncestorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.ParentID,
			&i.FileName,
			&i.IsDir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, slug, user_id, physical_file_id, parent_id, file_name, is_dir, file_size, mime_type, is_starred, is_trashed, trashed_at, created_at, updated_at FROM user_files WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFileByID(ctx context.Context, id int64) (UserFile, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i UserFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.PhysicalFileID,
		&i.ParentID,
		&i.FileName,
		&i.IsDir,
		&i.FileSize,
		&i.MimeType,
		&i.IsStarred,
		&i.IsTrashed,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileBySlug = `-- name: GetFileBySlug :one
SELECT id, slug, user_id, physical_file_id, parent_id, file_name, is_dir, file_size, mime_type, is_starred, is_trashed, trashed_at, created_at, updated_at FROM user_files WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetFileBySlug(ctx context.Context, slug string) (UserFile, error) {
	row := q.db.QueryRow(ctx, getFileBySlug, slug)
	var i UserFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.PhysicalFileID,
		&i.ParentID,
		&i.FileName,
		&i.IsDir,
		&i.FileSize,
		&i.MimeType,
		&i.IsStarred,
		&i.IsTrashed,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileBySlugForUser = `-- name: GetFileBySlugForUser :one
SELECT id, slug, user_id, physical_file_id, parent_id, file_name, is_dir, file_size, mime_type, is_starred, is_trashed, trashed_at, created_at, updated_at FROM user_files WHERE slug = $1 AND user_id = $2 LIMIT 1
`

type GetFileBySlugForUserParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) GetFileBySlugForUser(ctx context.Context, arg GetFileBySlugForUserParams) (UserFile, error) {
	row := q.db.QueryRow(ctx, getFileBySlugForUser, arg.Slug, arg.UserID)
	var i UserFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.PhysicalFileID,
		&i.ParentID,
		&i.FileName,
		&i.IsDir,
		&i.FileSize,
		&i.MimeType,
		&i.IsStarred,
		&i.IsTrashed,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFilesByParent = `-- name: ListFilesByParent :many
SELECT id, slug, user_id, physical_file_id, parent_id, file_name, is_dir, file_size, mime_type, is_starred, is_trashed, trashed_at, created_at, updated_at FROM user_files
WHERE user_id = $1
  AND is_trashed = FALSE
  AND (
    ($2::bigint IS NULL AND parent_id IS NULL)
    OR
    ($2::bigint IS NOT NULL AND parent_id = $2::bigint)
  )
ORDER BY is_dir DESC, file_name ASC
LIMIT $4 OFFSET $3
`

type ListFilesByParentParams struct {
	UserID     int64       `json:"user_id"`
	ParentID   pgtype.Int8 `json:"parent_id"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListFilesByParent(ctx context.Context, arg ListFilesByParentParams) ([]UserFile, error) {
	rows, err := q.db.Query(ctx, listFilesByParent,
		arg.UserID,
		arg.ParentID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserFile
	for rows.Next() {
		var i UserFile
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UserID,
			&i.PhysicalFileID,
			&i.ParentID,
			&i.FileName,
			&i.IsDir,
			&i.FileSize,
			&i.MimeType,
			&i.IsStarred,
			&i.IsTrashed,
			&i.TrashedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarredFiles = `-- name: ListStarredFiles :many
SELECT id, slug, user_id, physical_file_id, parent_id, file_name, is_dir, file_size, mime_type, is_starred, is_trashed, trashed_at, created_at, updated_at FROM user_files
WHERE user_id = $1 AND is_starred = TRUE AND is_trashed = FALSE
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListStarredFilesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStarredFiles(ctx context.Context, arg ListStarredFilesParams) ([]UserFile, error) {
	rows, err := q.db.Query(ctx, listStarredFiles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserFile
	for rows.Next() {
		var i UserFile
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UserID,
			&i.PhysicalFileID,
			&i.ParentID,
			&i.FileName,
			&i.IsDir,
			&i.FileSize,
			&i.MimeType,
			&i.IsStarred,
			&i.IsTrashed,
			&i.TrashedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedFiles = `-- name: ListTrashedFiles :many
SELECT id, slug, user_id, physical_file_id, parent_id, file_name, is_dir, file_size, mime_type, is_starred, is_trashed, trashed_at, created_at, updated_at FROM user_files
WHERE user_id = $1 AND is_trashed = TRUE
ORDER BY trashed_at DESC
LIMIT $2 OFFSET $3
`

type ListTrashedFilesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTrashedFiles(ctx context.Context, arg ListTrashedFilesParams) ([]UserFile, error) {
	rows, err := q.db.Query(ctx, listTrashedFiles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserFile
	for rows.Next() {
		var i UserFile
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UserID,
			&i.PhysicalFileID,
			&i.ParentID,
			&i.FileName,
			&i.IsDir,
			&i.FileSize,
			&i.MimeType,
			&i.IsStarred,
			&i.IsTrashed,
			&i.TrashedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFile = `-- name: MoveFile :exec
UPDATE user_files
SET parent_id = $2, updated_at = NOW()
WHERE id = $1
`

type MoveFileParams struct {
	ID       int64       `json:"id"`
	ParentID pgtype.Int8 `json:"parent_id"`
}

func (q *Queries) MoveFile(ctx context.Context, arg MoveFileParams) error {
	_, err := q.db.Exec(ctx, moveFile, arg.ID, arg.ParentID)
	return err
}

const renameFile = `-- name: RenameFile :exec
UPDATE user_files
SET file_name = $2, updated_at = NOW()
WHERE id = $1
`

type RenameFileParams struct {
	ID       int64  `json:"id"`
	FileName string `json:"file_name"`
}

func (q *Queries) RenameFile(ctx context.Context, arg RenameFileParams) error {
	_, err := q.db.Exec(ctx, renameFile, arg.ID, arg.FileName)
	return err
}

const restoreFile = `-- name: RestoreFile :exec
UPDATE user_files
SET is_trashed = FALSE, trashed_at = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RestoreFile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, restoreFile, id)
	return err
}

const setStarred = `-- name: SetStarred :exec
UPDATE user_files
SET is_starred = $2, updated_at = NOW()
WHERE id = $1
`

type SetStarredParams struct {
	ID        int64 `json:"id"`
	IsStarred bool  `json:"is_starred"`
}

func (q *Queries) SetStarred(ctx context.Context, arg SetStarredParams) error {
	_, err := q.db.Exec(ctx, setStarred, arg.ID, arg.IsStarred)
	return err
}

const setTrashed = `-- name: SetTrashed :exec
UPDATE user_files
SET is_trashed = $2, trashed_at = CASE WHEN $2 THEN NOW() ELSE NULL END, updated_at = NOW()
WHERE id = $1
`

type SetTrashedParams struct {
	ID        int64 `json:"id"`
	IsTrashed bool  `json:"is_trashed"`
}

func (q *Queries) SetTrashed(ctx context.Context, arg SetTrashedParams) error {
	_, err := q.db.Exec(ctx, setTrashed, arg.ID, arg.IsTrashed)
	return err
}
