// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkNameConflict = `-- name: CheckNameConflict :one
SELECT id, slug, file_name, is_dir, file_size FROM user_files
WHERE user_id = $1
  AND is_trashed = FALSE
  AND file_name = $2
  AND is_system = $3
  AND (
    ($4::bigint IS NULL AND parent_id IS NULL)
    OR
    ($4::bigint IS NOT NULL AND parent_id = $4::bigint)
  )
LIMIT 1
`

type CheckNameConflictParams struct {
	UserID   int64       `json:"userId"`
	FileName string      `json:"fileName"`
	IsSystem bool        `json:"isSystem"`
	ParentID pgtype.Int8 `json:"parentId"`
}

type CheckNameConflictRow struct {
	ID       int64  `json:"id"`
	Slug     string `json:"slug"`
	FileName string `json:"fileName"`
	IsDir    bool   `json:"isDir"`
	FileSize int64  `json:"fileSize"`
}

func (q *Queries) CheckNameConflict(ctx context.Context, arg CheckNameConflictParams) (CheckNameConflictRow, error) {
	row := q.db.QueryRow(ctx, checkNameConflict,
		arg.UserID,
		arg.FileName,
		arg.IsSystem,
		arg.ParentID,
	)
	var i CheckNameConflictRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.FileName,
		&i.IsDir,
		&i.FileSize,
	)
	return i, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO user_files (
    slug,
    user_id,
    physical_file_id,
    parent_id,
    parent_slug,
    file_name,
    is_dir,
    file_size,
    mime_type,
    file_category,
    is_system,
    system_kind
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, slug, user_id, physical_file_id, parent_id, file_name, is_dir, file_size, mime_type, is_starred, is_trashed, trashed_at, created_at, updated_at, file_category, parent_slug, is_system, system_kind
`

type CreateFileParams struct {
	Slug           string      `json:"slug"`
	UserID         int64       `json:"userId"`
	PhysicalFileID pgtype.Int8 `json:"physicalFileId"`
	ParentID       pgtype.Int8 `json:"parentId"`
	ParentSlug     pgtype.Text `json:"parentSlug"`
	FileName       string      `json:"fileName"`
	IsDir          bool        `json:"isDir"`
	FileSize       int64       `json:"fileSize"`
	MimeType       pgtype.Text `json:"mimeType"`
	FileCategory   string      `json:"fileCategory"`
	IsSystem       bool        `json:"isSystem"`
	SystemKind     pgtype.Text `json:"systemKind"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (UserFile, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.Slug,
		arg.UserID,
		arg.PhysicalFileID,
		arg.ParentID,
		arg.ParentSlug,
		arg.FileName,
		arg.IsDir,
		arg.FileSize,
		arg.MimeType,
		arg.FileCategory,
		arg.IsSystem,
		arg.SystemKind,
	)
	var i UserFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.PhysicalFileID,
		&i.ParentID,
		&i.FileName,
		&i.IsDir,
		&i.FileSize,
		&i.MimeType,
		&i.IsStarred,
		&i.IsTrashed,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FileCategory,
		&i.ParentSlug,
		&i.IsSystem,
		&i.SystemKind,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM user_files WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const getAncestors = `-- name: GetAncestors :many
WITH RECURSIVE ancestors AS (
    SELECT uf.id, uf.slug, uf.parent_id, uf.file_name, uf.is_dir
    FROM user_files uf WHERE uf.id = $1
    UNION ALL
    SELECT f.id, f.slug, f.parent_id, f.file_name, f.is_dir
    FROM user_files f
    JOIN ancestors a ON f.id = a.parent_id
)
SELECT a.id, a.slug, a.parent_id, a.file_name, a.is_dir FROM ancestors a ORDER BY a.id ASC
`

type GetAncestorsRow struct {
	ID       int64       `json:"id"`
	Slug     string      `json:"slug"`
	ParentID pgtype.Int8 `json:"parentId"`
	FileName string      `json:"fileName"`
	IsDir    bool        `json:"isDir"`
}

func (q *Queries) GetAncestors(ctx context.Context, id int64) ([]GetAncestorsRow, error) {
	rows, err := q.db.Query(ctx, getAncestors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAncestorsRow
	for rows.Next() {
		var i GetAncestorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.ParentID,
			&i.FileName,
			&i.IsDir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredTrashedFiles = `-- name: GetExpiredTrashedFiles :many
SELECT uf.id, uf.user_id, uf.is_dir, uf.physical_file_id, uf.file_size
FROM user_files uf
WHERE uf.is_trashed = TRUE
  AND uf.is_system = FALSE
  AND uf.trashed_at < NOW() - INTERVAL '30 days'
`

type GetExpiredTrashedFilesRow struct {
	ID             int64       `json:"id"`
	UserID         int64       `json:"userId"`
	IsDir          bool        `json:"isDir"`
	PhysicalFileID pgtype.Int8 `json:"physicalFileId"`
	FileSize       int64       `json:"fileSize"`
}

func (q *Queries) GetExpiredTrashedFiles(ctx context.Context) ([]GetExpiredTrashedFilesRow, error) {
	rows, err := q.db.Query(ctx, getExpiredTrashedFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredTrashedFilesRow
	for rows.Next() {
		var i GetExpiredTrashedFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IsDir,
			&i.PhysicalFileID,
			&i.FileSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, slug, user_id, physical_file_id, parent_id, file_name, is_dir, file_size, mime_type, is_starred, is_trashed, trashed_at, created_at, updated_at, file_category, parent_slug, is_system, system_kind FROM user_files WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFileByID(ctx context.Context, id int64) (UserFile, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i UserFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.PhysicalFileID,
		&i.ParentID,
		&i.FileName,
		&i.IsDir,
		&i.FileSize,
		&i.MimeType,
		&i.IsStarred,
		&i.IsTrashed,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FileCategory,
		&i.ParentSlug,
		&i.IsSystem,
		&i.SystemKind,
	)
	return i, err
}

const getFileBySlug = `-- name: GetFileBySlug :one
SELECT id, slug, user_id, physical_file_id, parent_id, file_name, is_dir, file_size, mime_type, is_starred, is_trashed, trashed_at, created_at, updated_at, file_category, parent_slug, is_system, system_kind FROM user_files WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetFileBySlug(ctx context.Context, slug string) (UserFile, error) {
	row := q.db.QueryRow(ctx, getFileBySlug, slug)
	var i UserFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.PhysicalFileID,
		&i.ParentID,
		&i.FileName,
		&i.IsDir,
		&i.FileSize,
		&i.MimeType,
		&i.IsStarred,
		&i.IsTrashed,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FileCategory,
		&i.ParentSlug,
		&i.IsSystem,
		&i.SystemKind,
	)
	return i, err
}

const getFileBySlugForUser = `-- name: GetFileBySlugForUser :one
SELECT id, slug, user_id, physical_file_id, parent_id, file_name, is_dir, file_size, mime_type, is_starred, is_trashed, trashed_at, created_at, updated_at, file_category, parent_slug, is_system, system_kind FROM user_files WHERE slug = $1 AND user_id = $2 LIMIT 1
`

type GetFileBySlugForUserParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"userId"`
}

func (q *Queries) GetFileBySlugForUser(ctx context.Context, arg GetFileBySlugForUserParams) (UserFile, error) {
	row := q.db.QueryRow(ctx, getFileBySlugForUser, arg.Slug, arg.UserID)
	var i UserFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.PhysicalFileID,
		&i.ParentID,
		&i.FileName,
		&i.IsDir,
		&i.FileSize,
		&i.MimeType,
		&i.IsStarred,
		&i.IsTrashed,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FileCategory,
		&i.ParentSlug,
		&i.IsSystem,
		&i.SystemKind,
	)
	return i, err
}

const getSystemDirByKind = `-- name: GetSystemDirByKind :one
SELECT id, slug, user_id, physical_file_id, parent_id, file_name, is_dir, file_size, mime_type, is_starred, is_trashed, trashed_at, created_at, updated_at, file_category, parent_slug, is_system, system_kind FROM user_files
WHERE user_id = $1
  AND is_trashed = FALSE
  AND is_dir = TRUE
  AND is_system = TRUE
  AND system_kind = $2
  AND (
    ($3::bigint IS NULL AND parent_id IS NULL)
    OR
    ($3::bigint IS NOT NULL AND parent_id = $3::bigint)
  )
LIMIT 1
`

type GetSystemDirByKindParams struct {
	UserID     int64       `json:"userId"`
	SystemKind pgtype.Text `json:"systemKind"`
	ParentID   pgtype.Int8 `json:"parentId"`
}

func (q *Queries) GetSystemDirByKind(ctx context.Context, arg GetSystemDirByKindParams) (UserFile, error) {
	row := q.db.QueryRow(ctx, getSystemDirByKind, arg.UserID, arg.SystemKind, arg.ParentID)
	var i UserFile
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.PhysicalFileID,
		&i.ParentID,
		&i.FileName,
		&i.IsDir,
		&i.FileSize,
		&i.MimeType,
		&i.IsStarred,
		&i.IsTrashed,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FileCategory,
		&i.ParentSlug,
		&i.IsSystem,
		&i.SystemKind,
	)
	return i, err
}

const getUserFilesByPhysicalFileID = `-- name: GetUserFilesByPhysicalFileID :many
SELECT file_name, parent_slug FROM user_files
WHERE physical_file_id = $1 AND user_id = $2 AND is_trashed = FALSE
LIMIT 5
`

type GetUserFilesByPhysicalFileIDParams struct {
	PhysicalFileID pgtype.Int8 `json:"physicalFileId"`
	UserID         int64       `json:"userId"`
}

type GetUserFilesByPhysicalFileIDRow struct {
	FileName   string      `json:"fileName"`
	ParentSlug pgtype.Text `json:"parentSlug"`
}

func (q *Queries) GetUserFilesByPhysicalFileID(ctx context.Context, arg GetUserFilesByPhysicalFileIDParams) ([]GetUserFilesByPhysicalFileIDRow, error) {
	rows, err := q.db.Query(ctx, getUserFilesByPhysicalFileID, arg.PhysicalFileID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFilesByPhysicalFileIDRow
	for rows.Next() {
		var i GetUserFilesByPhysicalFileIDRow
		if err := rows.Scan(&i.FileName, &i.ParentSlug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFile = `-- name: MoveFile :exec
UPDATE user_files
SET parent_id = $2, parent_slug = $3, updated_at = NOW()
WHERE id = $1
`

type MoveFileParams struct {
	ID         int64       `json:"id"`
	ParentID   pgtype.Int8 `json:"parentId"`
	ParentSlug pgtype.Text `json:"parentSlug"`
}

func (q *Queries) MoveFile(ctx context.Context, arg MoveFileParams) error {
	_, err := q.db.Exec(ctx, moveFile, arg.ID, arg.ParentID, arg.ParentSlug)
	return err
}

const renameFile = `-- name: RenameFile :exec
UPDATE user_files
SET file_name = $2, updated_at = NOW()
WHERE id = $1
`

type RenameFileParams struct {
	ID       int64  `json:"id"`
	FileName string `json:"fileName"`
}

func (q *Queries) RenameFile(ctx context.Context, arg RenameFileParams) error {
	_, err := q.db.Exec(ctx, renameFile, arg.ID, arg.FileName)
	return err
}

const restoreFile = `-- name: RestoreFile :exec
UPDATE user_files
SET is_trashed = FALSE, trashed_at = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RestoreFile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, restoreFile, id)
	return err
}

const setStarred = `-- name: SetStarred :exec
UPDATE user_files
SET is_starred = $2, updated_at = NOW()
WHERE id = $1
`

type SetStarredParams struct {
	ID        int64 `json:"id"`
	IsStarred bool  `json:"isStarred"`
}

func (q *Queries) SetStarred(ctx context.Context, arg SetStarredParams) error {
	_, err := q.db.Exec(ctx, setStarred, arg.ID, arg.IsStarred)
	return err
}

const setTrashed = `-- name: SetTrashed :exec
UPDATE user_files
SET is_trashed = $2, trashed_at = CASE WHEN $2 THEN NOW() ELSE NULL END, updated_at = NOW()
WHERE id = $1
`

type SetTrashedParams struct {
	ID        int64 `json:"id"`
	IsTrashed bool  `json:"isTrashed"`
}

func (q *Queries) SetTrashed(ctx context.Context, arg SetTrashedParams) error {
	_, err := q.db.Exec(ctx, setTrashed, arg.ID, arg.IsTrashed)
	return err
}
