// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_levels.sql

package sqlc

import (
	"context"
)

const createLevel = `-- name: CreateLevel :one
INSERT INTO user_levels (user_id, level_code, level_name)
VALUES ($1, $2, $3)
RETURNING id, user_id, level_code, level_name, expires_at, created_at, updated_at
`

type CreateLevelParams struct {
	UserID    int64  `json:"user_id"`
	LevelCode string `json:"level_code"`
	LevelName string `json:"level_name"`
}

func (q *Queries) CreateLevel(ctx context.Context, arg CreateLevelParams) (UserLevel, error) {
	row := q.db.QueryRow(ctx, createLevel, arg.UserID, arg.LevelCode, arg.LevelName)
	var i UserLevel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LevelCode,
		&i.LevelName,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLevelByUserID = `-- name: GetLevelByUserID :one
SELECT id, user_id, level_code, level_name, expires_at, created_at, updated_at FROM user_levels WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetLevelByUserID(ctx context.Context, userID int64) (UserLevel, error) {
	row := q.db.QueryRow(ctx, getLevelByUserID, userID)
	var i UserLevel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LevelCode,
		&i.LevelName,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
