// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (slug, username, email, password_hash, register_method)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slug, username, email, password_hash, status, register_method, created_at, updated_at
`

type CreateUserParams struct {
	Slug           string `json:"slug"`
	Username       string `json:"username"`
	Email          string `json:"email"`
	PasswordHash   string `json:"passwordHash"`
	RegisterMethod string `json:"registerMethod"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Slug,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.RegisterMethod,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.RegisterMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, slug, username, email, password_hash, status, register_method, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.RegisterMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, slug, username, email, password_hash, status, register_method, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.RegisterMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySlug = `-- name: GetUserBySlug :one
SELECT id, slug, username, email, password_hash, status, register_method, created_at, updated_at FROM users WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetUserBySlug(ctx context.Context, slug string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySlug, slug)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.RegisterMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID     int64 `json:"id"`
	Status int16 `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}
