// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_storage_stats.sql

package sqlc

import (
	"context"
)

const atomicIncrementStorage = `-- name: AtomicIncrementStorage :one
UPDATE user_storage_stats
SET storage_used = storage_used + $1,
    updated_at = NOW()
WHERE user_id = $2
  AND storage_used + $1 <= storage_quota
RETURNING storage_used, storage_quota
`

type AtomicIncrementStorageParams struct {
	StorageUsed int64 `json:"storageUsed"`
	UserID      int64 `json:"userId"`
}

type AtomicIncrementStorageRow struct {
	StorageUsed  int64 `json:"storageUsed"`
	StorageQuota int64 `json:"storageQuota"`
}

func (q *Queries) AtomicIncrementStorage(ctx context.Context, arg AtomicIncrementStorageParams) (AtomicIncrementStorageRow, error) {
	row := q.db.QueryRow(ctx, atomicIncrementStorage, arg.StorageUsed, arg.UserID)
	var i AtomicIncrementStorageRow
	err := row.Scan(&i.StorageUsed, &i.StorageQuota)
	return i, err
}

const createStorageStats = `-- name: CreateStorageStats :one
INSERT INTO user_storage_stats (user_id, storage_quota)
VALUES ($1, $2)
RETURNING id, user_id, storage_used, storage_quota, updated_at
`

type CreateStorageStatsParams struct {
	UserID       int64 `json:"userId"`
	StorageQuota int64 `json:"storageQuota"`
}

func (q *Queries) CreateStorageStats(ctx context.Context, arg CreateStorageStatsParams) (UserStorageStat, error) {
	row := q.db.QueryRow(ctx, createStorageStats, arg.UserID, arg.StorageQuota)
	var i UserStorageStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StorageUsed,
		&i.StorageQuota,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorageStats = `-- name: GetStorageStats :one
SELECT id, user_id, storage_used, storage_quota, updated_at FROM user_storage_stats WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetStorageStats(ctx context.Context, userID int64) (UserStorageStat, error) {
	row := q.db.QueryRow(ctx, getStorageStats, userID)
	var i UserStorageStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StorageUsed,
		&i.StorageQuota,
		&i.UpdatedAt,
	)
	return i, err
}
