// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_transactions.sql

package sqlc

import (
	"context"
)

const countTransactionsByUser = `-- name: CountTransactionsByUser :one
SELECT COUNT(*) FROM user_transactions WHERE user_id = $1
`

func (q *Queries) CountTransactionsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO user_transactions (slug, user_id, transaction_no, type, amount_cents, currency, status, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, slug, user_id, transaction_no, type, amount_cents, currency, status, metadata, created_at, updated_at
`

type CreateTransactionParams struct {
	Slug          string `json:"slug"`
	UserID        int64  `json:"user_id"`
	TransactionNo string `json:"transaction_no"`
	Type          string `json:"type"`
	AmountCents   int64  `json:"amount_cents"`
	Currency      string `json:"currency"`
	Status        string `json:"status"`
	Metadata      []byte `json:"metadata"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (UserTransaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Slug,
		arg.UserID,
		arg.TransactionNo,
		arg.Type,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
		arg.Metadata,
	)
	var i UserTransaction
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UserID,
		&i.TransactionNo,
		&i.Type,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT id, slug, user_id, transaction_no, type, amount_cents, currency, status, metadata, created_at, updated_at FROM user_transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]UserTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserTransaction
	for rows.Next() {
		var i UserTransaction
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UserID,
			&i.TransactionNo,
			&i.Type,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
